modify eventhub reademe
Azure/azure-sdk-for-java pull request #14778
Opened 2020-09-03 09:30 UTC by yiliuTo

modify README files of spring cloud eventhub modules for the release

2020-09-03 14:40 UTC, saragluna requested changes
Generally great, but if we follow the [Link Guidelines](https://github.com/Azure/azure-sdk/blob/master/docs/policies/README-TEMPLATE.md#link-guidelines):
- No locale info should be contained in the URL.
- We should not use relative URLs.

And I suggest that we put the URLs together at the bottom of README file which will make the content short and easy to edit.

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-boot-starter-active-directory-b2c/README.md
> +For more information about setting loging in spring, please refer to the [official doc](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-logging)
typo in loging

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-eventhubs-stream-binder/README.md
>  microservice using **Spring Cloud Stream** based on [Azure Event Hub](https://azure.microsoft.com/en-us/services/event-hubs/) service.
Following the [Link Guidelines](https://github.com/Azure/azure-sdk/blob/master/docs/policies/README-TEMPLATE.md#link-guidelines) we should remove this `en-us` locale.

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-eventhubs-stream-binder/README.md
>  microservice using **Spring Cloud Stream** based on [Azure Event Hub](https://azure.microsoft.com/en-us/services/event-hubs/) service.
How about we put these links URL at the bottom of the file using reference links?

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-eventhubs-stream-binder/README.md
> +- [Eventhubs Multibinders Sample](../azure-spring-boot-samples/azure-spring-cloud-eventhubs-multibinders-sample)
same here

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-eventhubs-stream-binder/README.md
> +Please follow [instructions here](../CONTRIBUTING.md) to build from source or contribute.
same here.

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-eventhubs-kafka/README.md
> +- [Eventhubs Kafka Sample](../azure-spring-boot-samples/azure-spring-cloud-eventhubs-kafka-sample)
relative URL

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-eventhubs-kafka/README.md
> +Please follow [instructions here](../CONTRIBUTING.md) to build from source or contribute.
relative URL

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-eventhubs/README.md
> +Please follow [instructions here](../CONTRIBUTING.md) to build from source or contribute.
relative URL.

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-eventhubs/README.md
> +- [Eventhubs Integration Sample](../azure-spring-boot-samples/azure-spring-cloud-eventhubs-integration-sample)
relative URL.

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-integration-eventhubs/README.md
> +- [Eventhubs Integration Sample](../azure-spring-boot-samples/azure-spring-cloud-eventhubs-integration-sample)
relative URL.

2020-09-03 14:40 UTC, saragluna commented on sdk/spring/azure-spring-integration-eventhubs/README.md
> +Please follow [instructions here](../CONTRIBUTING.md) to build from source or contribute.
relative URL.

2020-09-04 05:57 UTC, yiliuTo commented
@saragluna If we seperate readme modification into multiple PRs, then will there be conflicts when we merge each of them?

2020-09-07 00:24 UTC, saragluna commented
If each PR modifies a subset of README files then it should be fine.

2020-09-07 07:27 UTC, saragluna approved these changes
LGTM.

2020-09-07 07:37 UTC, merged