Split aad starter with two modules based on different spring boot versions
Azure/azure-sdk-for-java pull request #14802
Opened 2020-09-04 01:36 UTC by moarychan

According to the two major versions of spring boot, split current module azure-active-directory-spring-boot-starter into two modules：
* 2.2.X, artifact id is azure-active-directory-spring-boot-2-2-starter
* 2.3.X, artifact id is azure-active-directory-spring-boot-2-3-starter

2020-09-04 05:42 UTC, chenrujun commented
/azp run java - spring - tests

2020-09-07 07:53 UTC, chenrujun requested changes

2020-09-07 07:53 UTC, chenrujun commented on sdk/spring/azure-spring-boot-2-2-starter-active-directory/pom.xml
> +      <version>5.2.8.RELEASE</version> <!-- {x-version-update;org.springframework:spring-web;external_dependency} -->
This should be `springboot22_org.springframework:spring-web`? I think spring-boot-2-2 and 2-3 depend on different version of spring-web.

2020-09-07 07:53 UTC, chenrujun commented on sdk/spring/azure-spring-boot-2-2-starter-active-directory/pom.xml
> +      <version>5.2.8.RELEASE</version> <!-- {x-version-update;org.springframework:spring-web;external_dependency} -->
we can use `update_version_for_external_dependencies.py` to get versions in spring-boot-2-2

2020-09-07 07:53 UTC, chenrujun commented on sdk/spring/azure-spring-boot-2-2-starter-active-directory/pom.xml
> +      <version>5.3.4.RELEASE</version> <!-- {x-version-update;org.springframework.security:spring-security-core;external_dependency} -->
Same to other dependencies related to spring.

2020-09-07 07:53 UTC, chenrujun commented on sdk/spring/azure-spring-boot-2-3-starter-active-directory/src/main/resources/aad.enable.config
> +dummy
Do we need to add `newline` at end of file?

2020-09-07 07:53 UTC, chenrujun commented on sdk/spring/azure-spring-boot/README.md
> +- [Spring Boot 2.2 for Azure Active Directory](../azure-spring-boot-2-2-starter-active-directory)
I think `Azure Active Directory for Spring Boot 2.2` will make more sense. Same to other items.

2020-09-07 07:54 UTC, chenrujun commented
/azp run java - spring - tests

2020-09-07 07:54 UTC, chenrujun commented
Hi, @moarychan , please resolve conflicts. 🙏

2020-09-07 07:56 UTC, moarychan commented
Will create new PR for this change.

2020-09-07 07:56 UTC, closed without merging

2020-09-07 08:04 UTC, moarychan commented
Hi @chenrujun, I will update the code based on your proposal, but not in the current branch, all starter versions are changed together in a new branch.