Again add a hyperlink to the Spring Cloud Readme file Java Development Kit(JDK)
Azure/azure-sdk-for-java pull request #15596
Opened 2020-09-24 07:19 UTC by ZhuXiaoBing-cn

update #15505

2020-09-24 07:22 UTC, chenrujun approved these changes
LGTM.

2020-09-24 07:58 UTC, zhoufenqin approved these changes

2020-09-25 05:53 UTC, saragluna requested changes
Thanks for adding these links. Overall is great, but one unintentional change is included. Let's change it and get this PR merged.

2020-09-25 05:53 UTC, saragluna commented on sdk/spring/azure-spring-cloud-servicebus-queue-stream-binder/README.md
> +[spring_cloud_stream_binder_service_bus_topic]: https://ghithub.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-servicebus-topic-binder-sample
Is this an unintentional change?

2020-09-25 05:55 UTC, ZhuXiaoBing-cn commented on sdk/spring/azure-spring-cloud-servicebus-queue-stream-binder/README.md
> +[spring_cloud_stream_binder_service_bus_topic]: https://ghithub.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-servicebus-topic-binder-sample
yes,I will change back

2020-09-25 06:04 UTC, saragluna approved these changes

2020-09-25 07:05 UTC, merged