Change groupId to com.azure and artifactId to azure-spring-cloud-starter-xxx
Azure/azure-sdk-for-java pull request #15771
Opened 2020-09-28 09:42 UTC by ZhuXiaoBing-cn

update #13523

2020-09-28 10:18 UTC, moarychan commented on sdk/spring/azure-spring-boot-starter-cosmosdb/README.md
> +[sample]: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-cosmosdb
should  sync code from azure master first

2020-09-28 10:25 UTC, moarychan requested changes
please comfirm with @wujack778  to avoid repeat modification.

2020-09-28 10:25 UTC, moarychan commented on sdk/spring/azure-spring-cloud-autoconfigure/pom.xml
> +                <include>com.azure:azure-spring-integration-servicebus:[1.3.0-beta.1]</include> <!-- {x-include-update;com.azure:azure-spring-integration-servicebus;current} -->
we can remove all the dependencies which the group id starts with `com.azure:xxx` in `bannedDependencies` part.

2020-09-28 10:29 UTC, moarychan commented
this file https://github.com/ZhuXiaoBing-cn/azure-sdk-for-java/blob/work/sdk/spring/ci.yml should be updated together.

2020-09-29 02:20 UTC, ZhuXiaoBing-cn commented
I am sorry that there are some problems in my repository and there are redundant submissions. I need to close this PR now.

2020-09-29 02:20 UTC, closed without merging

2020-09-29 02:27 UTC, chenrujun commented
Hi, @ZhuXiaoBing-cn , you can use `git push -f` to avoid creating `closed` PR.