Change groupId to com.azure and artifactId to azure-spring-cloud-starter-xxx
Azure/azure-sdk-for-java pull request #15792
Opened 2020-09-29 03:37 UTC by ZhuXiaoBing-cn

Change groupId to com.azure and artifactId to azure-spring-cloud-starter-xxx  #13523

2020-09-30 05:17 UTC, saragluna requested changes

2020-09-30 05:17 UTC, saragluna commented on eng/jacoco-test-coverage/pom.xml
> +      <artifactId>azure-spring-cloud-starter-servicebus-stream-binder-core</artifactId>
same here

2020-09-30 05:17 UTC, saragluna commented on eng/jacoco-test-coverage/pom.xml
> +      <artifactId>azure-spring-cloud-starter-stream-binder-test</artifactId>
same here

2020-09-30 05:17 UTC, saragluna commented on eng/jacoco-test-coverage/pom.xml
> +      <artifactId>azure-spring-cloud-starter-servicebus-topic-stream-binder</artifactId>
same here

2020-09-30 05:17 UTC, saragluna commented on eng/jacoco-test-coverage/pom.xml
> +      <artifactId>azure-spring-cloud-starter-servicebus-queue-stream-binder</artifactId>
same here

2020-09-30 05:17 UTC, saragluna commented on eng/jacoco-test-coverage/pom.xml
> +      <version>2.0.0-beta.1</version> <!-- {x-version-update;com.azure:azure-spring-cloud-starter-eventhubs-stream-binder;current} -->
same here

2020-09-30 05:17 UTC, saragluna commented on eng/versioning/version_client.txt
> +com.azure:azure-spring-cloud-starter-autoconfigure;2.0.0-beta.1;2.0.0-beta.1
Basically, if the original artifact does not contain the `starter`, we should not add them

2020-09-30 05:17 UTC, saragluna commented on eng/versioning/version_client.txt
> +com.azure:azure-spring-integration-storage;2.0.0-beta.1;2.0.0-beta.1
Please sort lines.

2020-09-30 05:17 UTC, saragluna commented on sdk/appconfiguration/azure-spring-cloud-feature-management/README.md
> +An example web application that uses the targeting feature filter is available in the [example project](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/az
Let's use reference links here.

2020-09-30 05:17 UTC, saragluna commented on sdk/appconfiguration/azure-spring-cloud-feature-management/README.md
> +To begin using the `TargetingFilter` in an application it must be added as a `@Bean` like any other Feature Filter. `TargetingFilter` relies on another `@Bean` to be added to the application, [`ITarg
Same here.

2020-09-30 05:17 UTC, saragluna commented on sdk/boms/azure-spring-boot-bom/pom.xml
> +      <artifactId>azure-spring-integration-storage</artifactId>
This is the wrong artifact.

2020-09-30 05:17 UTC, saragluna commented on sdk/boms/azure-spring-boot-bom/pom.xml
> +      <artifactId>azure-spring-integration-storage</artifactId>
We should use the starter here, not the integration module.

2020-09-30 05:17 UTC, saragluna commented on sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-integration/pom.xml
> +  <version>1.0.0</version> <!-- {x-version-update;com.azure:azure-spring-cloud-sample-eventhubs-integration;current} -->
Let's call this sample azure-spring-integration-sample-eventhubs.

2020-09-30 05:17 UTC, saragluna commented on sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-servicebus-integration/pom.xml
> +  <artifactId>azure-spring-cloud-sample-servicebus-integration</artifactId>
azure-spring-integration-sample-servicebus

2020-09-30 05:17 UTC, saragluna commented on sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-storage-resource/pom.xml
> +      <version>2.0.0-beta.1</version> <!-- {x-version-update;com.azure:azure-spring-integration-storage;current} -->
wrong artifact here

2020-09-30 05:17 UTC, saragluna commented on sdk/spring/pom.xml
> +    <module>azure-spring-boot-samples/azure-spring-cloud-sample-appconfiguration-conversion-initial</module>
sort lines

2020-09-30 08:08 UTC, ZhuXiaoBing-cn commented
@saragluna thanks,I have modified it according to your suggestion

2020-09-30 09:00 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-storage-queue/pom.xml
> -                <include>com.microsoft.azure:spring-cloud-azure-context:[1.3.0-beta.1]</include> <!-- {x-include-update;com.microsoft.azure:spring-cloud-azure-context;current} -->
same here

2020-09-30 09:00 UTC, saragluna commented on sdk/spring/azure-spring-cloud-storage/README.md
>  [//]: # ({x-version-update-start;com.microsoft.azure:spring-cloud-azure-storage;current})
same here

2020-09-30 09:01 UTC, saragluna commented on sdk/spring/azure-spring-integration-eventhubs/README.md
>  [//]: # ({x-version-update-start;com.microsoft.azure:spring-integration-eventhubs;current})
same here

2020-09-30 09:02 UTC, saragluna commented on sdk/spring/azure-spring-integration-eventhubs/pom.xml
> -                <include>com.microsoft.azure:spring-integration-azure-core:[1.3.0-beta.1]</include> <!-- {x-include-update;com.microsoft.azure:spring-integration-azure-core;current} -->
same here

2020-09-30 09:02 UTC, saragluna commented on sdk/spring/azure-spring-integration-servicebus/README.md
>  [//]: # ({x-version-update-start;com.microsoft.azure:spring-integration-servicebus;current})
+1

2020-09-30 09:02 UTC, saragluna commented on sdk/spring/azure-spring-integration-storage-queue/README.md
>  [//]: # ({x-version-update-start;com.microsoft.azure:spring-integration-storage-queue;current})
+1

2020-09-30 09:03 UTC, saragluna commented on sdk/spring/azure-spring-integration-storage-queue/pom.xml
> -                <include>com.microsoft.azure:spring-integration-azure-core:[1.3.0-beta.1]</include> <!-- {x-include-update;com.microsoft.azure:spring-integration-azure-core;current} -->
+1

2020-09-30 09:03 UTC, saragluna commented on sdk/spring/azure-spring-starter-storage/README.md
>  [//]: # ({x-version-update-start;com.microsoft.azure:spring-starter-azure-storage;current})
+1

2020-09-30 10:29 UTC, ZhuXiaoBing-cn commented
Update the above comments

2020-10-09 02:17 UTC, saragluna requested changes

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-context/README.md
> -    <version>2.0.0-beta.1</version>
We should keep the version here. Then the script will ensure groupid/artifactid/version is align with the tag.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-eventhubs-stream-binder/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-servicebus-queue-stream-binder/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-servicebus-stream-binder-core/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-servicebus-topic-stream-binder/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-cache/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-eventhubs-kafka/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-eventhubs/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-servicebus/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-starter-storage-queue/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-storage/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-integration-eventhubs/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-integration-servicebus/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-integration-storage-queue/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:17 UTC, saragluna commented on sdk/spring/azure-spring-starter-storage/README.md
> -    <version>2.0.0-beta.1</version>
same here.

2020-10-09 02:57 UTC, saragluna commented
/azp run java - spring - tests

2020-10-09 05:15 UTC, saragluna approved these changes
LGTM.

2020-10-09 06:45 UTC, saragluna commented
/check-enforcer override

2020-10-09 06:46 UTC, merged