fixes #17751
Azure/azure-sdk-for-java pull request #17753
Opened 2020-11-23 07:19 UTC by lu-cheng

Fixes #17751

2020-11-23 07:34 UTC, saragluna submitted a review, later dismissed

2020-11-23 07:34 UTC, saragluna commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CAuthorizationRequestResolver.java
> +        this.properties.getAdditional().put("p", userFlow);
Maybe we shouldn't directly manipulate the `additional` here.

2020-11-24 02:35 UTC, chenrujun requested changes

2020-11-24 02:35 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-active-directory-b2c/README.md
> +         additional:
Maybe `authenticate-additional-parameters` will make it easier to understand?

2020-11-24 02:35 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CAuthorizationRequestResolver.java
> +        final Map<String, Object> additional = new HashMap<>();
additionalParameters

2020-11-24 06:41 UTC, chenrujun commented
/azp run java - spring - ci

2020-11-24 08:18 UTC, chenrujun approved these changes
LGTM.

2020-11-24 08:37 UTC, chenrujun commented
/check-enforcer override

2020-11-24 08:39 UTC, merged