fix : azure-messaging-eventhubs test cases
Azure/azure-sdk-for-java pull request #17752
Opened 2020-11-23 05:51 UTC by gkanani

fix : #6479

2020-11-23 19:53 UTC, srnagar reviewed
@gkanani Thank you for your contribution. We want to keep the revapi checks for this package. So, the plugin configuration to skip this check should be removed from pom.xml.

2020-11-23 19:53 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/pom.xml
> +
Revapi checks should not be skipped. This plugin can be removed.

2020-11-23 19:53 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/implementation/EventHubReactorConnectionTest.java
> +            .verifyError();
What's the error we are verifying here? Can we also assert on the expected error?

2020-11-23 19:53 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/implementation/EventHubConnectionProcessorTest.java
> +        Assertions.assertNotNull(testRetryOption);
Assert the values of retry mode, maxDelay, maxRetries etc as well.

2020-11-25 13:43 UTC, gkanani commented
@srnagar  PTAL

2020-11-25 18:46 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/implementation/EventHubReactorConnectionTest.java
> +        System.out.println("-----------------" + connection.createSendLink("send-name", "test-entity-path", new AmqpRetryOptions()));
Remove print statement here.

2020-11-25 18:46 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/implementation/EventHubReactorConnectionTest.java
> +            .verifyError(NullPointerException.class);
I don't think the mocks are set up correctly for testing `createSendLink` and `createReceiveLink` - `NullPointerException` is not the expected behavior here. Also, these have to be in separate test methods as this method is for testing management channel. Send and receive should be in its own test methods.

2020-11-25 18:46 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/pom.xml
> +
nit: remove extra blank lines.

2020-11-27 06:52 UTC, gkanani commented
@srnagar PTAL

2020-12-07 19:34 UTC, srnagar requested changes

2020-12-07 19:34 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/implementation/EventHubReactorConnectionTest.java
> +        Assertions.assertNotNull(connection.createSendLink("send-name", "test-entity-path", new AmqpRetryOptions()));
`createSendLink` is an async operation and will always return a non-null `Mono` object which should be subscribed to verify that the link was created. See the unit test for `getsManagementChannel`. Something similar to this has to be done:
```java
 StepVerifier.create(connection.createSendLink())
            .assertNext(link -> Assertions.assertTrue(link instanceof ReactorSender))
            .verifyComplete();
```

2020-12-07 19:34 UTC, srnagar commented on sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/implementation/EventHubReactorConnectionTest.java
> +        Assertions.assertNotNull(connection.createReceiveLink("receiver-name", "test-entity-path", EventPosition.latest(), new ReceiveOptions()));
Same as above.

2022-03-04 11:04 UTC, closed without merging