fixes : Test Coverage for Azure KeyVault Keys
Azure/azure-sdk-for-java pull request #17868
Opened 2020-11-28 13:14 UTC by ksatwara

#6485

2020-12-01 01:01 UTC, vcolin7 commented on sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/KeyAsyncClientTest.java
> +        createEcKeyRunner((expected) -> client.createEcKey(expected));
It is important that we assert that the result of the operation is correct, so I would at least add one assertion like on the method above (`createRsaKey`).

2020-12-01 01:01 UTC, vcolin7 commented on sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/KeyClientTest.java
> +        createEcKeyRunner((expected) -> client.createEcKey(expected));
Same comment as above about assertions.

2020-12-01 01:01 UTC, vcolin7 commented on sdk/keyvault/azure-security-keyvault-keys/src/test/resources/session-records/createEcKey.json
> +      "Body" : "{\"key\":{\"kid\":\"https://azure-kv-tests2.vault.azure.net/keys/javaKeyTemp/dfa0588bcdb74b84954421a69260882d\",\"kty\":\"RSA\",\"key_ops\":[\"encrypt\",\"decrypt\",\"sign\",\"verify\
You will probably need to run a live test with a real Key Vault and record the operation. I can help you out if you have questions about how to do this :)

2020-12-02 12:43 UTC, ksatwara commented on sdk/keyvault/azure-security-keyvault-keys/src/test/resources/session-records/createEcKey.json
> +      "Body" : "{\"key\":{\"kid\":\"https://azure-kv-tests2.vault.azure.net/keys/javaKeyTemp/dfa0588bcdb74b84954421a69260882d\",\"kty\":\"RSA\",\"key_ops\":[\"encrypt\",\"decrypt\",\"sign\",\"verify\
@vcolin7 Thanks for the guide but i don't have live testing project so could you please assign me test project so i will work on that or is there any testing project which you can assign me so work more on that

2020-12-02 12:47 UTC, ksatwara commented on sdk/keyvault/azure-security-keyvault-keys/src/test/resources/session-records/createEcKey.json
> +      "Body" : "{\"key\":{\"kid\":\"https://azure-kv-tests2.vault.azure.net/keys/javaKeyTemp/dfa0588bcdb74b84954421a69260882d\",\"kty\":\"RSA\",\"key_ops\":[\"encrypt\",\"decrypt\",\"sign\",\"verify\
moreover I also message to @joshfree about the same on Gitter but still no reply so i am asking you for the same.

2020-12-02 20:48 UTC, vcolin7 requested changes

2020-12-02 20:48 UTC, vcolin7 commented on sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/KeyAsyncClientTest.java
> +        createEcKeyRunner((expected) -> assertNotNull(client.createEcKey(expected)));
I think we can use `assertKeyEquals` like the method above to verify the created key contains the same characteristics we sent in the payload.

```suggestion
        createEcKeyRunner((expected) -> StepVerifier.create(client.createEcKey(expected))
            .assertNext(response -> assertKeyEquals(expected, response))
            .verifyComplete());
```

2020-12-02 20:48 UTC, vcolin7 commented on sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/KeyClientTest.java
> +        createEcKeyRunner((expected) -> assertNotNull(client.createEcKey(expected)));
Same comment as above :)

```suggestion
        createEcKeyRunner((expected) -> StepVerifier.create(client.createEcKey(expected))
            .assertNext(response -> assertKeyEquals(expected, response))
            .verifyComplete());
```

2020-12-02 21:45 UTC, vcolin7 commented on sdk/keyvault/azure-security-keyvault-keys/src/test/resources/session-records/createEcKey.json
> +      "Body" : "{\"key\":{\"kid\":\"https://azure-kv-tests2.vault.azure.net/keys/javaKeyTemp/dfa0588bcdb74b84954421a69260882d\",\"kty\":\"RSA\",\"key_ops\":[\"encrypt\",\"decrypt\",\"sign\",\"verify\
As far as I know we do not provide live applications for the community to test on, however, it you can [create an Azure Subscription for free](https://azure.microsoft.com/en-us/services/key-vault/), as well as an [Azure Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/keys/quick-create-portal). You can find more details on how to get started [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#getting-started) and [here](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-java).

If you wish to record tests yourself, you would need to pass the details of your Azure Key Vault as environment variables with the following names: `ARM_CLIENTID`, `ARM_CLIENTKEY` and `AZURE_TENANT_ID`. You will also need to set the `AZURE_TEST_MODE` environment variable to `RECORD`. After running the desired test, the recording can be found in the `target/session-records` as a file with the following name: `<test-name>.json`. I can also give you a hand if you get stuck at some point of the process.

As an alternative, I can record the test myself and push the recording to your branch :)

2020-12-03 19:59 UTC, vcolin7 requested changes

2020-12-03 19:59 UTC, vcolin7 commented on sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/KeyClientTest.java
> +        createEcKeyRunner((expected) -> assertKeyEquals(expected, client.createEcKey(expected)));
We should do the same for both clients.

```suggestion
        createEcKeyRunner((expected) -> StepVerifier.create(client.createEcKey(expected))
            .assertNext(response -> assertKeyEquals(expected, response))
            .verifyComplete());
```

2022-03-04 11:04 UTC, closed without merging