ACS Chat: Preview 3 refactor
Azure/azure-sdk-for-java pull request #17910
Opened 2020-12-02 01:16 UTC by danielgerlag

- Ran AutoRest against the latest swagger to regenerate code
- Refactored client code to be in-line with swagger changes
  - Split client into Chat client and Thread client
  - Added idempotency header to `createChatThread`
  - Add paging support to `listParticipants` and `listReadReceipts'
- Re-recorded live test sessions

2020-12-03 00:14 UTC, juancamilor requested changes

2020-12-03 00:47 UTC, angiurgiu commented on sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/ChatThreadAsyncClient.java
> +                        listParticipantsOptions.getMaxPageSize(),
Here (and everywhere we do listParticipantsOptions.get...) we should have a null check on listParticipantsOptions

Check out the other methods that had pagination already, they should have null checks before invoking the threadClient with options

2020-12-03 00:47 UTC, angiurgiu commented on sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/ChatThreadAsyncClient.java
> +    public PagedFlux<ChatMessageReadReceipt> listReadReceipts(ListReadReceiptOptions listReadReceiptOptions) {
Same comment, take precautions against NullReferenceExceptions

2020-12-03 00:47 UTC, angiurgiu commented on sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/models/CreateChatThreadOptions.java
> +    private String repeatabilityRequestID;
Id instead of ID

2020-12-07 17:35 UTC, juancamilor approved these changes

2020-12-07 22:09 UTC, merged