Add scopes for on-demand=true client
Azure/azure-sdk-for-java pull request #18173
Opened 2020-12-16 07:45 UTC by lzc-1997-abel

Add scopes for on-demand=true client and login with azure client

2020-12-16 08:18 UTC, chenrujun requested changes

2020-12-16 08:18 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapi/AzureActiveDirectoryResourceServerClientConfiguration.java
> +            false);
Delete booleam parameter, use different class for webapp and webapi.
```
AADClientRegistrationRepository
AADWebAppClientRegistrationRepository
AADWebApiClientRegistrationRepository
```

2020-12-16 08:18 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AzureActiveDirectoryConfiguration.java
> +        }
```
if (authz.isOnDemand()) {
    if()...
    if()...
}
```

2020-12-16 08:18 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AzureActiveDirectoryConfiguration.java
>          result.scope(authz.getScopes());
result.scope(scopes);

2020-12-16 08:18 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/test/java/com/azure/spring/aad/webapp/AzureActiveDirectoryConfigurationTest.java
> +                assertEquals("azure", clients.get(0).getRegistrationId());
Add test for both configurations.

2020-12-16 08:18 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AzureActiveDirectoryConfiguration.java
>          return new AzureClientRegistrationRepository(
Rename this file to `AADWebAppConfiguration`

2020-12-16 08:18 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapi/AzureActiveDirectoryResourceServerClientConfiguration.java
>          return new AzureClientRegistrationRepository(
Rename this file to `AADWebApiConfiguration`

2020-12-17 05:24 UTC, chenrujun commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADWebAppConfiguration.java
> +        }
This is not updated yet.

2020-12-17 05:24 UTC, lzc-1997-abel commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADWebAppConfiguration.java
> +        }
sorry , i missed that

2020-12-17 05:25 UTC, chenrujun commented
/azp run java - spring - tests

2020-12-17 06:35 UTC, lzc-1997-abel commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADWebAppConfiguration.java
> +        }
done

2020-12-17 23:23 UTC, chenrujun commented
Hi, @lzc-1997-abel , please resolve the conflicts.

2020-12-18 02:28 UTC, chenrujun approved these changes

2020-12-18 02:42 UTC, chenrujun commented
/check-enforcer override

2020-12-18 02:43 UTC, merged