add dependency for keyvault certificates starter
Azure/azure-sdk-for-java pull request #18411
Opened 2020-12-31 07:02 UTC by lzc-1997-abel

add dependency for keyvault certificates starter

2020-12-31 13:37 UTC, mnriem reviewed
Why is this being added?

2021-01-02 06:48 UTC, lzc-1997-abel commented
HI,@mnriem, I'm not sure why I can't reply to your content. I'll explain it here
The dependency used in starter is optional in azure-security-keyvault-jca, which will cause ClassNoDefException when azure-spring-boot-sample-keyvault-certificates is started.
https://github.com/Azure/azure-sdk-for-java/blob/5af23e5e66a2fb3312a248596771adf26ece1689/sdk/keyvault/azure-security-keyvault-jca/pom.xml#L129-L134

2021-01-02 13:20 UTC, mnriem commented
It is an optional dependency in azure-security-keyvault-jca, because it is relocated and shaded in. The dependency should not be added to the starter.

2021-01-04 00:11 UTC, chenrujun commented
Hi, @lzc-1997-abel , I checked jar file. `httpclient5` will be shaded in even though it is an optional dependency.

Refs: 
![image](https://user-images.githubusercontent.com/13167207/103492203-32bee700-4e64-11eb-805f-ecd98de07800.png)

>cause ClassNoDefException when azure-spring-boot-sample-keyvault-certificates is started.

Could you please share the log of stack trace?

2021-01-04 09:06 UTC, lzc-1997-abel commented
My fault, there is no problem starting the project through maven, it may be my idea configuration is wrong, I will modify the readme and fix this pr.

2021-01-05 01:27 UTC, chenrujun requested changes

2021-01-05 01:27 UTC, chenrujun commented on sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-certificates/README.md
> +This sample illustrates how to use [Azure Spring Boot Starter Key Vault Certificates ](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-keyvault-certificat
Please move link to `<!-- LINKS -->` at the end of this file.

2021-01-05 01:27 UTC, chenrujun commented on sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-certificates/README.md
> +We need to store certificate `self-signed` into Azure Key Vault with the following steps: [store certificate ](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-sta
Same here.

2021-01-05 01:27 UTC, chenrujun commented on sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-certificates/README.md
> +mvn spring-boot:run
Good point. 👍

2021-01-05 05:07 UTC, chenrujun approved these changes

2021-01-05 05:08 UTC, merged