Update key vault readme
Azure/azure-sdk-for-java pull request #18971
Opened 2021-02-04 07:30 UTC by lzc-1997-abel

2021-02-08 01:15 UTC, chenrujun requested changes

2021-02-08 01:15 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/README.md
> +3. Select **Create**.
In the display page, `3.` changed to `1.`. Please investigate how to display `3.`.
![image](https://user-images.githubusercontent.com/13167207/107165017-57baf280-69ec-11eb-982f-8cddb3afa056.png)

2021-02-08 01:15 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/README.md
> +   * Pricing tier.
Detailed description can be replaced with: 
```
Input `Subscription`, `Resource group`, `Key vault name` and `Pricing tier`, then click `Review + Create`.
```

2021-02-08 01:15 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/README.md
> +   When you have specified the options listed above, select **Review + Create**, review the specifications and select **Create** to Key vault. The deployment will take several minutes.
Use `click` instead of `select`. Same to other places.

2021-02-08 01:15 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/README.md
> +![Create Certificates](resource/create-certificates.png)
Add step numbers in the screenshot. Same to other screenshots.

2021-02-08 01:15 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/README.md
> +1. Select **Show portal menu**, then **Azure Active Directory**.
```
1. Click `Azure Active Directory`.
1. Click `App registration`.
1. Click `New registration`
etc..
```

Refs: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-active-directory/README.md#register-the-application-in-azure-ad

2021-02-08 01:15 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/README.md
> +        SSLConnectionSocketFactory csf = new SSLConnectionSocketFactory(sslContext, allowAll);
Please add Java sample code in `src/samples/java`.
Refs: https://github.com/Azure/azure-sdk-for-java/blame/master/sdk/spring/azure-spring-boot-starter-active-directory/README.md#L312

2021-02-09 09:04 UTC, lzc-1997-abel commented
Hi,@mnriem,please help to review this pr.
Can I add the code from the readme file to the example like this?

2021-02-10 06:25 UTC, chenrujun commented
/azp run java - spring - ci

2021-02-19 08:56 UTC, chenrujun approved these changes

2021-02-19 08:56 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/README.md
> +    ![Specify the options](resource/specify-the-options.png)
Swap `2` and `3` in the image.

2021-02-19 09:21 UTC, chenrujun commented
/check-enforcer override

2021-02-19 09:22 UTC, merged