App configuration Docs Update
Azure/azure-sdk-for-java pull request #19312
Opened 2021-02-18 18:41 UTC by mrm9084

2021-03-02 01:12 UTC, saragluna requested changes

2021-03-02 01:14 UTC, mrm9084 commented on sdk/appconfiguration/azure-spring-cloud-starter-appconfiguration-config/README.md
> +The Web Provider can be connect to your Azure App Configuration store via an Azure Event Grid Web Hook to trigger a refresh event. By adding the Spring Actuator as a dependency you can add App Config
I mean the configurations need to be set for servicebus. We will have an ms docs doc on how to do it.

2021-03-02 01:16 UTC, saragluna commented on sdk/appconfiguration/azure-spring-cloud-starter-appconfiguration-config/README.md
> +The Web Provider can be connect to your Azure App Configuration store via an Azure Event Grid Web Hook to trigger a refresh event. By adding the Spring Actuator as a dependency you can add App Config
Do we need to change the description here now? Setting up multiple instances of jms starter doesn't make much sense to me.

2021-03-04 19:01 UTC, mrm9084 commented on sdk/appconfiguration/azure-spring-cloud-starter-appconfiguration-config/README.md
> +The Web Provider can be connect to your Azure App Configuration store via an Azure Event Grid Web Hook to trigger a refresh event. By adding the Spring Actuator as a dependency you can add App Config
@saragluna Tried to fix the wording. This works the same as the Spring Bus Refresh.

2021-03-05 06:17 UTC, saragluna approved these changes
LGTM.

2021-03-25 21:47 UTC, merged