Update Dependency Versions
Azure/azure-sdk-for-java pull request #19320
Opened 2021-02-19 00:51 UTC by alzimmermsft

This PR updates dependency versions.

2021-02-19 01:18 UTC, weidongxu-microsoft approved these changes

2021-02-19 02:22 UTC, chenrujun requested changes
IMU, this PR should be merged after all out of band release finished.

2021-02-22 17:16 UTC, conniey approved these changes

2021-02-25 23:31 UTC, chenrujun commented
FYI: Spring integration team will do out of band release around 2021-03-04. Please don't merge this PR before we finished release.

2021-03-08 21:52 UTC, alzimmermsft commented
Closing as these version upgrades were made in another PR

2021-03-08 21:52 UTC, closed without merging