Update versions for Spring obo release
Azure/azure-sdk-for-java pull request #19579
Opened 2021-03-03 09:07 UTC by backwind1233

2021-03-03 09:08 UTC, backwind1233 commented
/azp run java - spring - tests

2021-03-03 09:11 UTC, stliu approved these changes
LGTM

2021-03-04 06:07 UTC, chenrujun requested changes

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-aad/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-application/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-core/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-cosmos/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-keyvault/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-parent/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-selenium-common/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-servicebus-jms/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-boot-test-storage/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
Here.

2021-03-04 06:07 UTC, chenrujun commented on sdk/spring/azure-spring-cloud-test-eventhubs/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
It will not be released.

2021-03-04 08:06 UTC, backwind1233 commented
/check-enforcer override

2021-03-04 08:39 UTC, chenrujun approved these changes
LGTM.

2021-03-04 09:21 UTC, merged

2021-03-04 23:07 UTC, eightstars commented on sdk/spring/azure-spring-cloud-test-eventhubs/CHANGELOG.md
> +## 1.0.0 (2021-03-03)
よくできました

2021-03-04 23:58 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-data-gremlin/CHANGELOG.md
> +## 3.0.0-beta.1 (2021-03-03)
Hi, @backwind1233 , it should not be released.