Add javadoc codesnippets and unit tests for DynamicRequest and DynamicResponse
Azure/azure-sdk-for-java pull request #20289
Opened 2021-03-31 08:02 UTC by srnagar

This PR updates JavaDoc to use codesnippets doclet and adds unit tests for DynamicRequest.

2021-03-31 19:51 UTC, alzimmermsft approved these changes

2021-04-01 01:36 UTC, chenrujun requested changes

2021-04-01 01:36 UTC, chenrujun commented on eng/versioning/external_dependencies.txt
> +javax.json:javax.json-api;1.1
Please use 1.1.4.
Refs: 
1. https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/external_dependencies.txt#L1
2. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/scripts/spring_managed_external_dependencies.txt#L461

2021-04-01 07:09 UTC, chenrujun approved these changes
LGTM about eng/versioning/external_dependencies.txt.

2021-04-01 08:22 UTC, merged