Support setting redirect uri.
Azure/azure-sdk-for-java pull request #21249
Opened 2021-05-08 08:04 UTC by han-gao

New features:  Support user to set redirect-uri.

2021-05-10 03:15 UTC, stliu commented on e -i HEAD~2
> +[33mcommit ec132e144a6f60accba0750aae473a63db3c58ea[m[33m ([m[1;36mHEAD -> [m[1;32mEnable_property_azure.activedirectory.redirect-uri-template[m[33m)[m
why you changed this file

2021-05-10 03:16 UTC, stliu commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/aad/AADAuthenticationProperties.java
> -                                throw new IllegalStateException("onDemand only support authorization_code grant type. ");
this change is not necessary

2021-05-10 03:17 UTC, stliu commented on sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/aad/AADAuthenticationProperties.java
> -     * @deprecated Now the redirect-url-template is not configurable.
so, this is a regression?

2021-05-10 03:17 UTC, stliu commented
could you link this PR to the github issue?

2021-05-18 01:33 UTC, chenrujun commented
Hi, @han-gao , please resolve the conflicts.

2021-05-18 07:51 UTC, chenrujun requested changes

2021-05-18 07:51 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-active-directory/README.md
> +This starter supports Reset Redirection Endpoint(authorization server to return responses containing authorization credentials to the client via the resource owner user-agent). Developers can customi
Delete `This starter supports Reset Redirection Endpoint(authorization server to return responses containing authorization credentials to the client via the resource owner user-agent).`,

Just keep `Developers can customize the redirect-uri.`

2021-05-18 07:51 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-active-directory/README.md
> +![what-is-redirect-uri](resource/what-is-redirect-uri.png)
Delete the text in the picture. Just point out the `redirect_uri`.

2021-05-18 07:51 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-active-directory/README.md
> +We need to configure the same redirect-uri as application.yml:
Keep 4 spaces at the beginning of this line.

2021-05-18 07:51 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-active-directory/README.md
> +
Same here.

2021-05-18 07:51 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-active-directory/README.md
> +After we set redirect-uri-template, we need to update `SecurityConfigurerAdapter`:
Here.

2021-05-18 07:51 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-active-directory/README.md
> +                .loginProcessingUrl("/{your-path-prefix}")
Why `your-path-prefix`? Maybe it should be `your redirect uri`?

2021-05-18 09:18 UTC, chenrujun approved these changes
LGTM.

2021-05-18 09:18 UTC, chenrujun commented
/check-enforcer override

2021-05-18 09:19 UTC, merged