Testing to add spring boot 2.3.x version support
Azure/azure-sdk-for-java pull request #21258
Opened 2021-05-10 08:22 UTC by moarychan

This PR is for testing the azure spring modules based on the spring boot 2.3.x version in a new service directory.

### Changelog:
- Add the new service directory `spring-2-3`.
- Check out from tag `azure-spring-boot_3.2.0` which is based on spring boot version `2.3.5.RELEASE` version.
- Upgrade spring boot version to `2.3.10.RELEASE`.
- Increase azure spring modules version.

2021-05-10 09:49 UTC, saragluna commented
/azp run prepare-pipelines

2021-05-10 11:31 UTC, saragluna commented
/azp run java - spring-2-3 - ci

2021-05-11 01:40 UTC, saragluna commented
Hi @mitchdenny, this is a try to support Spring versions side by side https://github.com/Azure/azure-sdk-for-java/issues/15512. Could you please take a look at this.

2021-05-11 01:42 UTC, saragluna commented
/azp run java - spring-2-3 - ci

2021-05-12 02:01 UTC, saragluna commented
/azp run java - spring-2-3 - ci

2021-05-12 02:13 UTC, saragluna commented
@mitchdenny to change the artifact names having a spring version identifier will not work for us, since we've released our libs for Spring Boot 2.3.x and 2.4.x. So we're giving multiple directories a try now, to see whether it is feasible this way.

2021-05-12 09:00 UTC, saragluna commented
/azp run java - spring - tests

2021-05-13 00:22 UTC, saragluna commented
/azp run java - spring - tests

2021-05-13 07:40 UTC, saragluna commented
/azp run java - spring - tests

2021-05-13 09:28 UTC, saragluna commented
/azp run java - spring - tests

2021-05-13 09:34 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-13 09:49 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-14 01:58 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-14 01:58 UTC, saragluna commented
/azp run java - spring - tests

2021-05-17 01:53 UTC, saragluna commented
/azp run java - spring - tests

2021-05-17 01:53 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-18 05:22 UTC, saragluna commented
/azp run java - spring - tests

2021-05-18 05:22 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-19 08:53 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-19 08:54 UTC, saragluna commented
/azp run java - spring - tests

2021-05-20 02:56 UTC, saragluna commented
/azp run java - spring - tests

2021-05-20 02:56 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-21 06:18 UTC, saragluna commented
/azp run java - spring - tests
/azp run java - spring-2-3 - tests

2021-05-21 06:20 UTC, saragluna commented
/azp run java - spring - tests

2021-05-21 06:20 UTC, saragluna commented
/azp run java - spring-2-3 - tests

2021-05-24 01:15 UTC, mitchdenny commented
I can't review this PR anymore because the number of files is too large (causes the browser to hang). Perhaps that is a sign that we should be looking at making these changes in more digestible chunks?

2021-05-24 01:25 UTC, mitchdenny requested changes
This PR can't be merged yet since we haven't resolved the "should we" question. But there are probably approaches that we'd want to take to make a more general solution to side-by-side versioning IF we want to take this approach.

It certainly needs to be broken down into smaller charges. A PR with 1296 changes is probably not viable to review sensibly.

2021-05-24 03:16 UTC, JonathanGiles commented on sdk/spring-2-3/AzureSpringCodeStyle.xml
> +<code_scheme name="AzureSpringCodeStyle20200910" version="173">
I suspect this file should just be removed before the PR is merged.

2021-05-24 03:36 UTC, moarychan commented
@mitchdenny , sorry for confusing you, I have put this PR as a draft and it should not be merged to master. Thanks for your suggestion, I will continue to test other questions.

2021-06-22 02:42 UTC, closed without merging