updated keyvault jca changelog for local jre keystore certificates
Azure/azure-sdk-for-java pull request #22133
Opened 2021-06-08 02:47 UTC by michaelqi793

2021-06-08 07:14 UTC, chenrujun requested changes

2021-06-08 07:14 UTC, chenrujun commented on sdk/keyvault/azure-security-keyvault-jca/CHANGELOG.md
> +- Support the local JRE key store certificates. [#21845](https://github.com/Azure/azure-sdk-for-java/pull/21845)
```
Load JRE key store certificates to AzureKeyVault key store. ([#21845](https://github.com/Azure/azure-sdk-for-java/pull/21845))
```

2021-06-08 07:14 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/CHANGELOG.md
> +- Support the local JRE key store certificates. [#21845](https://github.com/Azure/azure-sdk-for-java/pull/21845)
Same here.

2021-06-09 00:43 UTC, michaelqi793 commented on sdk/keyvault/azure-security-keyvault-jca/CHANGELOG.md
> +- Support the local JRE key store certificates. [#21845](https://github.com/Azure/azure-sdk-for-java/pull/21845)
Done

2021-06-09 05:37 UTC, chenrujun requested changes

2021-06-09 05:37 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/CHANGELOG.md
> +- Load JRE key store certificates to AzureKeyVault key store. ([#21845](https://github.com/Azure/azure-sdk-for-java/pull/21845))
We need `### New Features` here.

2021-06-09 05:56 UTC, michaelqi793 commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/CHANGELOG.md
> +- Load JRE key store certificates to AzureKeyVault key store. ([#21845](https://github.com/Azure/azure-sdk-for-java/pull/21845))
Done

2021-06-09 07:09 UTC, chenrujun approved these changes
LGTM.

2021-06-09 07:10 UTC, merged