update readme for storage libraries to include BOM information.
Azure/azure-sdk-for-java pull request #22858
Opened 2021-07-08 19:36 UTC by pallavit

2021-08-06 21:37 UTC, pallavit commented
soft ping, review please.
/cc: @amishra-dev , @gapra-msft , @jaschrep-msft , @kasobol-msft , @rickle-msft

2021-08-07 04:58 UTC, amishra-dev requested changes
Putting a wait on this while the conversation on email is resolved.

2021-08-09 21:15 UTC, joshfree approved these changes

2021-08-09 21:15 UTC, joshfree commented on sdk/storage/azure-storage-blob-batch/README.md
> +Please include the azure-sdk-bom to your project to take dependency on GA version of the library. In the following snippet, replace the {bom_version_to_target} placeholder with the version number.
> Please include the azure-sdk-bom to your project to take dependency on GA version of the library.

Please include the azure-sdk-bom to your project to take **a** dependency on **the General Availability (GA)** version of the library.

2021-08-09 21:15 UTC, joshfree commented on sdk/storage/azure-storage-blob-cryptography/README.md
> +Please include the azure-sdk-bom to your project to take dependency on GA version of the library. In the following snippet, replace the {bom_version_to_target} placeholder with the version number.
> Please include the azure-sdk-bom to your project to take dependency on GA version of the library.

Please include the azure-sdk-bom to your project to take **a** dependency on **the General Availability (GA)** version of the library.

2021-08-09 21:15 UTC, joshfree commented on sdk/storage/azure-storage-blob/README.md
> +Please include the azure-sdk-bom to your project to take dependency on GA version of the library. In the following snippet, replace the {bom_version_to_target} placeholder with the version number.
> Please include the azure-sdk-bom to your project to take dependency on GA version of the library.

Please include the azure-sdk-bom to your project to take **a** dependency on **the General Availability (GA)** version of the library.

2021-08-09 21:15 UTC, joshfree commented on sdk/storage/azure-storage-common/README.md
> +Please include the azure-sdk-bom to your project to take dependency on GA version of the library. In the following snippet, replace the {bom_version_to_target} placeholder with the version number.
> Please include the azure-sdk-bom to your project to take dependency on GA version of the library.

Please include the azure-sdk-bom to your project to take **a** dependency on **the General Availability (GA)** version of the library.

2021-08-09 21:15 UTC, joshfree commented on sdk/storage/azure-storage-file-datalake/README.md
> +Please include the azure-sdk-bom to your project to take dependency on GA version of the library. In the following snippet, replace the {bom_version_to_target} placeholder with the version number.
> Please include the azure-sdk-bom to your project to take dependency on GA version of the library.

Please include the azure-sdk-bom to your project to take **a** dependency on **the General Availability (GA)** version of the library.

2021-08-09 21:15 UTC, joshfree commented on sdk/storage/azure-storage-file-share/README.md
> +Please include the azure-sdk-bom to your project to take dependency on GA version of the library. In the following snippet, replace the {bom_version_to_target} placeholder with the version number.
> Please include the azure-sdk-bom to your project to take dependency on GA version of the library.

Please include the azure-sdk-bom to your project to take **a** dependency on **the General Availability (GA)** version of the library.

2021-08-09 21:15 UTC, joshfree commented on sdk/storage/azure-storage-queue/README.md
> +Please include the azure-sdk-bom to your project to take dependency on GA version of the library. In the following snippet, replace the {bom_version_to_target} placeholder with the version number.
> Please include the azure-sdk-bom to your project to take dependency on GA version of the library.

Please include the azure-sdk-bom to your project to take **a** dependency on **the General Availability (GA)** version of the library.

2021-08-09 21:15 UTC, joshfree commented
Adding `Do Not Merge` label, so ensure only the Storage team merges this.

2021-08-19 19:00 UTC, pallavit commented
Given our sync on Tuesday - can we merge these changes? 
/cc: @joshfree , @amishra-dev @kasobol-msft

2021-08-24 16:51 UTC, rickle-msft approved these changes

2021-08-25 16:43 UTC, pallavit commented
@rickle-msft thanks for the review.

2021-09-08 22:21 UTC, amishra-dev approved these changes

2021-09-08 22:27 UTC, joshfree commented
@rickle-msft @amishra-dev any concerns with merging this now?

2021-09-29 19:26 UTC, merged