Upgrade to spring boot 2.5.4.
Azure/azure-sdk-for-java pull request #23709
Opened 2021-08-23 01:30 UTC by ZhuXiaoBing-cn

Upgrade to spring boot 2.5.4.

2021-08-23 01:47 UTC, ZhuXiaoBing-cn commented
/azp run java - spring - tests

2021-08-23 01:47 UTC, ZhuXiaoBing-cn commented
/azp run java - cosmos - tests

2021-08-23 01:47 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-08-23 06:00 UTC, ZhuXiaoBing-cn commented
/azp run java - spring - tests

2021-08-23 06:00 UTC, ZhuXiaoBing-cn commented
/azp run java - cosmos - tests

2021-08-23 06:00 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-08-23 23:37 UTC, chenrujun commented
Hi, @ZhuXiaoBing-cn .

1. I think it's ready to merge now.
2. I suggest to push these commits in one time, to avoid unnecessary checks:
![image](https://user-images.githubusercontent.com/13167207/130532751-5d5d8115-921b-4766-82fd-e00da187c379.png)

2021-08-29 23:17 UTC, chenrujun commented
/azp run java - spring - tests

2021-08-29 23:17 UTC, chenrujun commented
/azp run java - cosmos - tests

2021-08-29 23:17 UTC, chenrujun commented
/azp run java - keyvault - tests

2021-08-30 08:56 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-08-30 09:21 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-08-30 23:28 UTC, chenrujun commented on sdk/keyvault/azure-security-keyvault-jca/src/main/resources/module-info.java
> +    exports com.azure.security.keyvault.jca.implementation.certificates;
Why this line is required?

2021-08-31 02:25 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-08-31 03:27 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-08-31 04:56 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-08-31 09:54 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-09-01 01:20 UTC, ZhuXiaoBing-cn commented
hi, @zhichengliu12581, Please take a look at the problem. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1074180&view=logs&j=4d65ddb6-61b1-57ce-0321-ae337fc9c5ee&t=56b2bd38-4099-51d8-2503-bd1f55f7f9cf&l=3403

2021-09-01 02:32 UTC, chenrujun requested changes

2021-09-01 02:32 UTC, chenrujun commented on sdk/keyvault/ci.yml
> +      - sdk/keyvault/azure-security-test-keyvault-jca/
Is this necessary?

2021-09-01 02:32 UTC, chenrujun commented on sdk/keyvault/ci.yml
> +      - sdk/keyvault/azure-security-test-keyvault-jca/
Same here.

2021-09-01 02:32 UTC, chenrujun commented on sdk/keyvault/azure-security-keyvault-jca/src/main/resources/module-info.java
> +    exports com.azure.security.keyvault.jca.implementation.certificates;
Can we delete this line now?

2021-09-01 02:32 UTC, chenrujun commented on sdk/keyvault/tests.yml
> -          safeName: azuresecuritytestkeyvaultjca
This should not be deleted.

2021-09-01 02:32 UTC, chenrujun commented on sdk/keyvault/azure-security-keyvault-jca/src/test/java/com/azure/security/keyvault/jca/KeyVaultKeyManagerTest.java
> +@EnabledIfEnvironmentVariable(named = "AZURE_KEYVAULT_CERTIFICATE_NAME", matches = "myalias")
If it can not be enabled, it's OK to enable it in another PR. We can merge this PR first.

2021-09-01 05:31 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-09-01 05:31 UTC, ZhuXiaoBing-cn commented
/azp run java - spring - tests

2021-09-01 05:31 UTC, ZhuXiaoBing-cn commented
/azp run java - cosmos - tests

2021-09-01 10:08 UTC, ZhuXiaoBing-cn commented
/azp run java - cosmos - tests

2021-09-01 10:08 UTC, ZhuXiaoBing-cn commented
/azp run java - spring - tests

2021-09-02 02:44 UTC, ZhuXiaoBing-cn commented on sdk/keyvault/ci.yml
> +      - sdk/keyvault/azure-security-test-keyvault-jca/
TODO

2021-09-02 02:45 UTC, ZhuXiaoBing-cn commented on sdk/keyvault/ci.yml
> -      - sdk/keyvault/azure-security-test-keyvault-jca/
TODO

2021-09-02 02:45 UTC, ZhuXiaoBing-cn commented on sdk/keyvault/ci.yml
> -      - sdk/keyvault/azure-security-test-keyvault-jca/pom.xml
TODO

2021-09-02 04:55 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-09-02 06:45 UTC, ZhuXiaoBing-cn commented
/azp run java - keyvault - tests

2021-09-02 07:59 UTC, ZhuXiaoBing-cn commented
Hi, @vcolin7, Please help me look at this issue https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1078541&view=logs&j=62d76672-1784-5f46-1111-1156ba23c418&t=9209e3d9-ec88-5bdf-ab6a-f765d314ed31&l=3060.
It seems to be a coverage issue.

2021-09-02 23:20 UTC, vcolin7 commented
Hi @ZhuXiaoBing-cn, I ran some local and live tests and it looks like the Key Vault Administration code coverage is above the threshold, so I don't know why the pipeline keeps marking this step as a failure. I think you should be able to ignore this for the time being and merge this PR so you are unblocked. I will investigate separately.

2021-09-03 01:22 UTC, zhichengliu12581 commented
LGTM

2021-09-03 01:23 UTC, zhichengliu12581 approved these changes

2021-09-03 01:46 UTC, ZhuXiaoBing-cn commented
/check-enforcer override

2021-09-03 05:18 UTC, ZhuXiaoBing-cn commented
Hi, @chenrujun, the related conversation has been resolved, please review it.

2021-09-06 01:17 UTC, chenrujun requested changes

2021-09-06 01:17 UTC, chenrujun commented on sdk/keyvault/azure-security-keyvault-jca/src/test/java/com/azure/security/keyvault/jca/KeyVaultKeyManagerTest.java
> +@EnabledIfEnvironmentVariable(named = "AZURE_KEYVAULT_CERTIFICATE_NAME", matches = "myalias")
AS we discussed, we'd better recover this. 

Fine, we can ignore this for now, and update it in next PR. 
(cc: @zhichengliu12581 , FYI.)

2021-09-06 01:17 UTC, chenrujun commented on sdk/keyvault/ci.yml
> -
Is this necessary?

2021-09-06 01:17 UTC, chenrujun commented on sdk/keyvault/tests.yml
> +          safeName: azuresecuritytestkeyvaultjca
It's better to not include unnecessary change.

2021-09-06 01:17 UTC, chenrujun commented on sdk/spring/azure-spring-boot-starter-keyvault-certificates/CHANGELOG.md
> +## 3.1.0-beta.1 (Unreleased)
Don't change this.

2021-09-06 06:20 UTC, chenrujun approved these changes
LGTM.

2021-09-06 07:11 UTC, merged

2021-09-08 21:54 UTC, kushagraThapar commented
/azp run java - cosmos - ci