Removed Beta tag from Bulk, Batch and Patch APIs. Deleted Deprecated classes
Azure/azure-sdk-for-java pull request #24433
Opened 2021-09-28 19:06 UTC by kushagraThapar

* Removed Beta tag from Bulk, Batch and Patch APIs. 
* Deleted Deprecated classes

2021-09-28 21:06 UTC, kushagraThapar commented
/azp run java - cosmos - tests

2021-09-28 22:51 UTC, xinlian12 approved these changes
LGTM. Thanks

2021-09-29 14:35 UTC, xinlian12 commented on sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosBulkOperationResponse.java
> +     * Get BatchContext
Do we need to add more detailed comment?

2021-09-29 14:35 UTC, xinlian12 commented on sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosBulkOperationResponse.java
> +     * Get BatchContext
do we need more detailed comments?

2021-09-29 14:36 UTC, xinlian12 requested changes
Request change to block from merging.

2021-09-29 16:48 UTC, azure-sdk commented
API changes have been detected in this PR. You can review API changes [here](https://apiview.dev/Assemblies/Review/279517cfb2024219bad36656055c9a5b?diffOnly=True&diffRevisionId=da93192d51474ece9d631fdbdc6a5f1c)

2021-11-02 19:11 UTC, milismsft approved these changes

2021-11-02 20:30 UTC, kushagraThapar commented
/azp run java - cosmos - test

2021-11-02 20:31 UTC, kushagraThapar commented
/azp run java - cosmos - tests

2021-11-02 20:33 UTC, xinlian12 approved these changes

2021-11-02 20:43 UTC, azure-sdk commented
API changes have been detected in `com.azure:azure-cosmos`. You can review API changes [here](https://apiview.dev/Assemblies/Review/279517cfb2024219bad36656055c9a5b?diffOnly=True&diffRevisionId=9ec08aa089934816bc603cbdc239fa3e)

2021-11-02 21:17 UTC, moderakh approved these changes
LGTM. thanks @kushagraThapar

2021-11-03 11:54 UTC, FabianMeiswinkel approved these changes
LGTM

2021-11-03 15:47 UTC, kushagraThapar commented
/azp run java - cosmos - tests

2021-11-03 19:20 UTC, merged