Add @ConditionalOnBean on CosmosReactiveRepositoriesAutoConfiguration
Azure/azure-sdk-for-java pull request #25237
Opened 2021-11-08 10:10 UTC by backwind1233

1. rename `azure.cosmos.repositories` to `spring.cloud.azure.cosmos.repositories`
2. add @ConditionalOnProperty on CosmosReactiveRepositoriesAutoConfiguration

2021-11-09 06:48 UTC, saragluna requested changes

2021-11-09 06:48 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/data/cosmos/CosmosReactiveRepositoriesAutoConfiguration.java
> +@ConditionalOnBean(ReactiveCosmosTemplate.class)
This auto-configuration must be put after the auto-configuration of ReactiveCosmosTemplate, using @ConfigurationAfter, to make sure the condition won't be evaluated before the auto-configuration of ReactiveCosmosTemplate

2021-11-09 06:48 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/data/cosmos/CosmosRepositoriesAutoConfiguration.java
> +@ConditionalOnProperty(prefix = "spring.cloud.azure.cosmos.repositories",
Same here, should this depend on a CosmosTemplate bean?

2021-11-15 07:42 UTC, backwind1233 commented
@saragluna Do you still have any concern about this PR？

2021-11-15 09:14 UTC, saragluna commented
@backwind1233 one more thing, we should make sure all integration tests passed for such changes.

2021-11-15 09:27 UTC, backwind1233 commented
/azp run java - spring - tests

2021-11-15 09:41 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/data/cosmos/CosmosReactiveRepositoriesAutoConfiguration.java
> +@AutoConfigureAfter(ReactiveCosmosTemplate.class)
Is this change intentional? Is ReactiveCosmosTemplate an auto-configuration class?

2021-11-15 10:41 UTC, saragluna approved these changes
LGTM.

2021-11-16 02:41 UTC, backwind1233 commented
/azp run java - spring - tests

2021-11-16 02:54 UTC, merged