fix batch consuming issue
Azure/azure-sdk-for-java pull request #25664
Opened 2021-11-24 07:58 UTC by jialigit

fix the batch checkpoint issue

# Description

fix batch consuming issue for checkpointing.

2021-11-24 09:07 UTC, yiliuTo commented
/azp run java - spring - tests

2021-11-24 09:10 UTC, yiliuTo requested changes

2021-11-25 02:16 UTC, jialigit commented on sdk/spring/azure-spring-cloud-stream-binder-eventhubs/src/test/resources/application.yaml
> +spring:
updated

2021-11-25 03:01 UTC, yiliuTo commented
/azp run java - spring - tests

2021-11-25 04:50 UTC, yiliuTo approved these changes
LGTM

2021-11-25 04:50 UTC, yiliuTo commented
/check-enforcer override

2021-11-25 04:51 UTC, merged