map value of `azure_client_id` to `managed-identity-client-id`
Azure/azure-sdk-for-java pull request #25711
Opened 2021-11-26 01:29 UTC by backwind1233

2021-11-26 01:32 UTC, backwind1233 commented
@saragluna please help review this PR

2021-11-26 02:50 UTC, stliu commented
this only take a env value but not properties

considering the following configuration

`credential.client-id=xxxx`, will this value be assigned to the `credential.managed-identity-client-id` as well?

I think the it's better to impl something like :

`credential.managed-identity-client-id = ${credential.client-id}` at autoconfiguration's property binding stage

2021-12-02 13:37 UTC, saragluna commented
@backwind1233  will you address Strong's comment?

2021-12-15 08:55 UTC, saragluna requested changes

2021-12-15 08:55 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/test/java/com/azure/spring/cloud/autoconfigure/context/AzureGlobalConfigurationEnvironmentPostProcessorTest.java
> +        properties.put(AzureGlobalProperties.PREFIX + ".credential.managed-identity-client-id",
the value better follow the same pattern, you can use the custom-managed-identity-client-id

2021-12-15 09:34 UTC, saragluna approved these changes
LGTM.

2021-12-16 02:27 UTC, merged