gh-25635
Azure/azure-sdk-for-java pull request #25764
Opened 2021-12-01 08:22 UTC by chenrujun

Fix #25635

2021-12-02 13:34 UTC, saragluna requested changes

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/cloudfoundry/AzureCfService.java
> +     * @param cfServiceName The CF Service name.
Service to service, and maybe we could call it Cloud Foundry instead of using CF here.

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubProperties.java
> +     * @return The checkpointStorageAccount.
checkpoint storage account.

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubProperties.java
> +     * @param checkpointStorageAccount The checkpointStorageAccount.
same here

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubProperties.java
> +     * @return The connectionString.
connection string.

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubProperties.java
> +     * @param connectionString The connectionString.
same here.

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubProperties.java
> +     * @return The checkpointAccessKey.
we should avoid using the parameter in the javadoc right?

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubProperties.java
> +     * @return The checkpointAccessKey.
Same for all in this class.

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/servicebus/AzureServiceBusAutoConfiguration.java
> +     * @param azureResourceManager The AzureResourceManager.
same here

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/servicebus/AzureServiceBusProperties.java
> +     * @return The AmqpRetryOptions.
same here

2021-12-02 13:34 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/servicebus/AzureServiceBusTopicAutoConfiguration.java
> +     * @return The ServiceBusTopicClientFactory.
same for these

2021-12-02 13:35 UTC, saragluna commented
We should avoid directly using the parameter name as the description for the parameter itself in the javadoc. Please update accordingly.

2021-12-03 01:08 UTC, chenrujun commented
Hi, @saragluna , Thanks for your review.

If we want to improve the quality of java doc, this task should be done by each area owner.
But now each area owner is busy with 4.0 related tasks.
And these contents will be changed a lot in version 4.0.
So I think we should not spend a lot of time on this now. 
Just finish the task in a short time is OK.

2021-12-08 02:33 UTC, saragluna commented
@chenrujun how about convert this pr to draft first?

2021-12-08 06:13 UTC, chenrujun commented
Closing this PR. Current plan is create another PR after 4.0 branch merged into main branch.

2021-12-08 06:13 UTC, closed without merging