Fix javadoc and url link warnings of api-reivew
Azure/azure-sdk-for-java pull request #25896
Opened 2021-12-08 09:23 UTC by backwind1233

As title:
It's mainly about the java doc warnings.

2021-12-08 09:26 UTC, backwind1233 commented
@saragluna please help review this PR.

2021-12-08 09:30 UTC, saragluna requested changes

2021-12-08 09:30 UTC, saragluna commented on sdk/spring/spring-cloud-azure-core/src/main/java/com/azure/spring/core/resource/AbstractAzureStorageProtocolResolver.java
> +     * For AzureStorageFileProtocolResolver, getStorageType() will return StorageType.FILE;
How about moving these descriptions to the implementation classes, as an abstract class, we perhaps won't know how many implementations it will have.

2021-12-09 02:14 UTC, saragluna approved these changes
LGTM.

2021-12-09 02:14 UTC, saragluna commented
Merging this pr now for the ci failed of some pipeline issues.

2021-12-09 02:15 UTC, merged