Add more description about how to upgrade external dependencies' version according to spring-boot-dependencies and spring-cloud-dependencies.
Azure/azure-sdk-for-java pull request #26059
Opened 2021-12-16 06:37 UTC by chenrujun

As title.

2021-12-16 06:38 UTC, chenrujun commented
Hi, @saragluna , please help to review this PR when you have time.

2021-12-16 10:32 UTC, saragluna requested changes

2021-12-16 10:32 UTC, saragluna commented on sdk/spring/scripts/README.md
> +1. Get `SPRING_BOOT_VERSION` from [spring-boot-dependencies tags](https://github.com/spring-projects/spring-boot/tags). Get `SPRING_CLOUD_VERSION` from [spring-boot-dependencies tags](https://github.
Need change:  Get `SPRING_CLOUD_VERSION` from [spring-boot-dependencies tags]

2021-12-16 23:21 UTC, chenrujun commented on sdk/spring/scripts/README.md
> +1. Get `SPRING_BOOT_VERSION` from [spring-boot-dependencies tags](https://github.com/spring-projects/spring-boot/tags). Get `SPRING_CLOUD_VERSION` from [spring-boot-dependencies tags](https://github.
Updated.

2021-12-20 05:21 UTC, saragluna approved these changes
LGTM.

2021-12-20 06:27 UTC, merged