Remove spring test modules
Azure/azure-sdk-for-java pull request #26158
Opened 2021-12-23 08:50 UTC by moarychan

The new features are supported in the 4.0 feature, and many modules have been refactored, 
so we plan to remove the `azure-spring-boot-test-xxx` modules to make the spring project structure cleaner, 
more unit tests should be included, some unit tests have been added in the previous 
PR https://github.com/Azure/azure-sdk-for-java/pull/25820, others will keep or remove.

Changelog:
- Remove `azure-spring-boot-test-application`
- `azure-spring-boot-test-core`
- `azure-spring-boot-test-cosmos`
- `azure-spring-boot-test-keyvault`
- `azure-spring-boot-test-parent`
- `azure-spring-boot-test-servicebus-jms`
- `azure-spring-boot-test-storage`
- `spring-cloud-azure-stream-binder-test`
- `spring-cloud-azure-test-parent`
- Move the ITs of `spring-cloud-azure-test-servicebus-binder` into `spring-cloud-azure-starter-stream-servicebus`
- Move the ITs of `azure-spring-boot-test-keyvault-certificate` into `spring-cloud-azure-starter-keyvault-certificates`

2021-12-29 07:49 UTC, Netyyyy commented
/azp run java - spring - tests

2021-12-29 10:30 UTC, Netyyyy commented
/azp run java - appconfiguration - tests

2022-01-07 02:17 UTC, Netyyyy commented
/azp run java - spring - tests

2022-01-07 02:54 UTC, moarychan commented
@saragluna , please help review, thanks!

2022-01-07 07:06 UTC, saragluna requested changes

2022-01-07 07:06 UTC, saragluna commented on sdk/spring/spring-cloud-azure-stream-binder-servicebus/pom.xml
> +        <groupId>org.apache.maven.plugins</groupId>
Why is this being added?

2022-01-07 07:06 UTC, saragluna commented on sdk/spring/spring-cloud-azure-test-eventhubs-binder/pom.xml
> +    </dependencies>
do we still need this?

2022-01-07 07:06 UTC, saragluna commented on sdk/spring/spring-cloud-azure-test-servicebus-binder/pom.xml
> +      </dependency>
same here

2022-01-07 07:50 UTC, moarychan commented on sdk/spring/spring-cloud-azure-stream-binder-servicebus/pom.xml
> +        <groupId>org.apache.maven.plugins</groupId>
😓

2022-01-07 07:51 UTC, moarychan commented on sdk/spring/spring-cloud-azure-test-eventhubs-binder/pom.xml
> +    </dependencies>
No, let me remove it.

2022-01-07 08:48 UTC, saragluna approved these changes
LGTM, thanks for the change!

2022-01-07 08:57 UTC, merged