Fix query plan cache initialization
Azure/azure-sdk-for-java pull request #26825
Opened 2022-02-02 08:35 UTC by kul

There is a 'memory leak' introduced due to below commit as the init(..) code path (via sync clients) does not initializes the cache to a size limited lru cache. In case the queries are not parameterized this can lead to the cache growing unbounded over time.

https://github.com/Azure/azure-sdk-for-java/commit/01ad248c46763435bbce35750e23297a46070f2d#diff-dd557c9356c91a57b6bc7ce3cff436e1fde4daaa2841a2de889b3a7da138afb4

2022-02-02 16:41 UTC, kushagraThapar commented
@mbhaskar  - can you please take a look at this.

2022-02-02 17:47 UTC, mbhaskar requested changes
Thanks @kul for identifying this. Left some review comments

2022-02-02 17:47 UTC, mbhaskar commented on sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java
> +            this.queryPlanCache = Collections.synchronizedMap(new SizeLimitingLRUCache(Constants.QUERYPLAN_CACHE_SIZE));
I feel we can skip initializing this here as it gets initialized in the client construction before init here: https://github.com/Azure/azure-sdk-for-java/blob/ff077373038ff09cf967ddab3d3cf4f0649ca60a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/AsyncDocumentClient.java#L230 -> 
https://github.com/Azure/azure-sdk-for-java/blob/ff077373038ff09cf967ddab3d3cf4f0649ca60a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java#L373

So the fix just would be deleting the line that initializes queryPlanCache here

```suggestion

```

2022-02-04 16:54 UTC, mbhaskar approved these changes
LGTM. Thanks. 
Please resolve conflicts and also make sure tests pass.

2022-02-09 23:12 UTC, kushagraThapar commented
/azp run java - cosmos - tests

2022-02-11 00:59 UTC, merged