Update AAD auto-config conditional and split OAuth2AuthorizedClientManager configuration
Azure/azure-sdk-for-java pull request #26964
Opened 2022-02-09 08:32 UTC by moarychan

Fixes https://github.com/Azure/azure-sdk-for-java/issues/26915.

Changelog:
- Update AAD, AAD B2C auto-config condition.
- Split OAuth2AuthorizedClientManager configuration based on application type.
- Remove unnecessary revapi configuration.

2022-02-09 09:14 UTC, Netyyyy commented
/azp run java - spring - tests

2022-02-11 08:26 UTC, chenrujun requested changes

2022-02-11 08:26 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-autoconfigure/src/test/java/com/azure/spring/cloud/autoconfigure/aad/implementation/conditions/AllWebApplicationConditionTests.java
> +    static class WebApplicationConditionConfig extends Config { }
Keep it align to condition class name. Here is should be `AllWebApplicationConditionConfig`. 
No need to change it if you rename `AllWebApplicationConditionConfig` to `WebApplicationCondition`.

2022-02-14 01:45 UTC, moarychan commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AADAuthenticationFilterAutoConfiguration.java
> +@ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.SERVLET)
Yes, forgot this one.

2022-02-14 02:07 UTC, moarychan commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/conditions/AllWebApplicationCondition.java
> +public final class AllWebApplicationCondition extends AbstractApplicationTypeCondition {
Good.

2022-02-14 02:40 UTC, moarychan commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/conditions/AbstractApplicationTypeCondition.java
> +    protected abstract Function<AADApplicationType, Boolean> getNoMatchCondition();
I use `abstract boolean isNonTargetApplicationType(AADApplicationType applicationType); ` instead.

2022-02-14 03:29 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/conditions/AbstractApplicationTypeCondition.java
> +    protected abstract Function<AADApplicationType, Boolean> getNoMatchCondition();
`isTargetApplicationType` is easier to understand when implement this method.
About the hint in Intellij, can we fix by creating another method:
```
abstract boolean isTargetApplicationType(AADApplicationType applicationType);

private boolean isNotTargetApplicationType(AADApplicationType applicationType){ // Non -> Not
    return !isNonTargetApplicationType(applicationType);
}

```

2022-02-14 06:05 UTC, chenrujun requested changes

2022-02-14 06:05 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AADOAuth2ClientConfiguration.java
> +    public static class WebApplicationOAuth2AuthorizedClientManagerConfiguration {
nit: Rename to `WebApplicationWithoutResourceServerOAuth2AuthorizedClientManagerConfiguration`

2022-02-14 08:19 UTC, chenrujun approved these changes
LGTM.

2022-02-14 08:25 UTC, merged

2022-02-15 01:10 UTC, saragluna commented
@moarychan, will this be targeting both 3.x and 4.x?

2022-02-15 04:09 UTC, moarychan commented
As per discussed, this is an enhancement for AAD, only target the 4.0 branch enough.