Apply Traits to Communication
Azure/azure-sdk-for-java pull request #27010
Opened 2022-02-10 19:17 UTC by kasobol-msft

This works spans from https://github.com/Azure/azure-sdk-for-java/pull/26562  where interfaces to capture commonly occurring APIs at client builders has been created.

2022-02-10 19:23 UTC, azure-sdk commented
API changes have been detected in `com.azure:azure-communication-chat`. You can review API changes [here](https://apiview.dev/Assemblies/Review/0fb435b436cf4e22b2460a23a7926fb3?diffOnly=True&diffRevisionId=3a5e8d1e47b5465496d8132dfc75221e)

2022-02-10 19:23 UTC, azure-sdk commented
API changes have been detected in `com.azure:azure-communication-networktraversal`. You can review API changes [here](https://apiview.dev/Assemblies/Review/1b0943091dfd4727b0726d542ea5e7d0?diffOnly=True&diffRevisionId=6a9cf840180f409aaf42660d3d8ef633)

2022-02-10 19:23 UTC, azure-sdk commented
API changes have been detected in `com.azure:azure-communication-phonenumbers`. You can review API changes [here](https://apiview.dev/Assemblies/Review/9a40f73bc7e2475099735122c3f7b4ff?diffOnly=True&diffRevisionId=56eac88c73bf443c85c75247a5b9b759)

2022-02-10 23:43 UTC, whisper6284 commented on sdk/communication/azure-communication-phonenumbers/src/test/java/com/azure/communication/phonenumbers/PhoneNumbersClientBuilderTest.java
> +        assertThrows(IllegalStateException.class, () -> setupBuilderWithHttpClientWithCredential(this.clientBuilder)
I don't understand these two tests. Why is IllegalStateException thrown?

2022-02-11 02:39 UTC, azure-sdk commented
API changes have been detected in `com.azure:azure-communication-networktraversal`. You can review API changes [here](https://apiview.dev/Assemblies/Review/1b0943091dfd4727b0726d542ea5e7d0?diffOnly=True&diffRevisionId=37d105f521f94461b7e1671b003f4071)

2022-02-24 19:45 UTC, kasobol-msft commented
/azp run java - azure-communication-phonenumbers - tests

2022-02-24 23:47 UTC, kasobol-msft commented
/azp run java - azure-communication-sms - tests

2022-02-25 00:02 UTC, Shamkh approved these changes

2022-02-25 09:55 UTC, petrsvihlik requested changes
Identity 
- ✅ code changes lgtm 
- ❌ missing a changelog entry

2022-02-25 10:33 UTC, srnagar approved these changes

2022-02-25 10:33 UTC, srnagar commented on sdk/communication/azure-communication-callingserver/CHANGELOG.md
> +-
Remove this line (or call out the new retryOptions API on the builder)

2022-02-25 10:53 UTC, AikoBB commented on sdk/communication/azure-communication-identity/src/main/java/com/azure/communication/identity/CommunicationIdentityClientBuilder.java
> +    public CommunicationIdentityClientBuilder retryOptions(RetryOptions retryOptions) {
could you pls mention the addition of this setter in the CHANGELOG

2022-02-25 17:23 UTC, AikoBB approved these changes

2022-02-27 15:01 UTC, petrsvihlik approved these changes

2022-02-28 19:40 UTC, merged