update revapi of spring package for main branch
Azure/azure-sdk-for-java pull request #27078
Opened 2022-02-14 02:09 UTC by Netyyyy

Remove suppression of spring package and add targeted suppression.

2022-02-16 02:58 UTC, Netyyyy commented
/azp run java - spring - tests

2022-02-16 09:16 UTC, Netyyyy commented
/azp run java - spring - tests

2022-02-17 03:28 UTC, saragluna requested changes

2022-02-17 03:28 UTC, saragluna commented on eng/code-quality-reports/src/main/resources/revapi/revapi.json
> +        },
Why are these two needed? I remember we don't use these libraries.

2022-02-17 03:28 UTC, saragluna commented on eng/code-quality-reports/src/main/resources/revapi/revapi.json
> +        },
What is this rule used for?

2022-02-18 06:17 UTC, Netyyyy commented
/azp run java - spring - tests

2022-02-18 17:43 UTC, alzimmermsft approved these changes

2022-02-21 03:23 UTC, Netyyyy commented
/check-enforcer override

2022-02-21 03:23 UTC, merged