Support Spring native feature for Spring Cloud Azure libraries in 4.0 branch
Azure/azure-sdk-for-java pull request #27300
Opened 2022-02-25 00:40 UTC by moarychan

Make the Spring Cloud Azure modules work with GraalVM using Spring AOT capability, this PR is based on the PR https://github.com/Azure/azure-sdk-for-java/pull/25035.

Changelog:
- Update module azure-sot-graalvm-support, add storage fetures;
- Update Spring Cloud Azure modules to support Spring AOT feature, it's used to enable Spring Native feature for all Spring Cloud Azure libraries.
- [Todo] Support Spring Native feature for all Azure Spring Boot samples.

2022-03-02 05:37 UTC, saragluna requested changes

2022-03-02 05:37 UTC, saragluna commented on sdk/parents/azure-client-sdk-parent/pom.xml
> +              <execution>
do we need this?

2022-03-02 05:45 UTC, saragluna commented on sdk/aot/azure-aot-graalvm-support/src/main/java/com/azure/aot/graalvm/support/implementation/features/StorageFileShareFeature.java
> +package com.azure.aot.graalvm.support.implementation.features;
should the package name include spring, like com.azure.spring.xxx

2022-03-02 10:35 UTC, moarychan commented on sdk/spring/spring-cloud-azure-native-configuration/src/main/java/com/azure/spring/cloud/autoconfigure/keyvault/secrets/KeyVaultSecretsHints.java
> +//}
Yes, just tested

2022-03-03 02:08 UTC, Netyyyy commented
/azp run java - spring - ci

2022-04-02 08:00 UTC, closed without merging