auto label 'azure-spring' for PRs with github labeler action
Azure/azure-sdk-for-java pull request #28117
Opened 2022-04-08 08:05 UTC by stliu

This pr uses [Github Labeler action](https://github.com/marketplace/actions/labeler) to add labels for PRs

https://github.com/Azure/azure-sdk-for-java/issues/28019

2022-04-13 07:09 UTC, saragluna requested changes
IIRC the PR changes codes related to sdk/spring have already added the azure-spring label automatically. https://github.com/Azure/azure-sdk-for-java/pulls?q=is%3Apr+is%3Aopen+label%3Aazure-spring

2022-04-13 07:09 UTC, saragluna commented on .github/labeler.yml
> +  - sdk/bomx/spring-cloud-azure-dependencies/**/*
bom

2022-04-14 02:09 UTC, stliu commented on .github/labeler.yml
> +  - sdk/bomx/spring-cloud-azure-dependencies/**/*
fixed

2022-04-19 15:19 UTC, JimSuplizio reviewed
@stliu I would like to know what purpose this serves and why this is necessary? In the future, I would appreciate that being in the description of PRs of this nature.

2022-04-19 18:10 UTC, weshaggard requested changes
At this time we are not ready to start taking a dependency on github actions/workflows. 

For tagging we already use the fabric bot which already handles tagging of PRs and issues based on paths. See https://github.com/Azure/azure-sdk-for-java/blob/main/.github/fabricbot.json if you need help please talk with @jsquire.

2022-04-20 01:22 UTC, stliu commented
okay, seems this already done by another bot, closing this one

2022-04-20 01:22 UTC, closed without merging

2022-04-21 12:26 UTC, jsquire commented
The main challenge with Fabric Bot to replicate this is the lack of support for glob or regex patterns for path identification.    It supports only `StartsWith` semantics, which means that each child path intended to be covered by an individual Fabric Bot entry in the rule.