Update resourcemanager service poms to use correct dependencies
Azure/azure-sdk-for-java pull request #28367
Opened 2022-04-18 19:12 UTC by srnagar

This PR fixes the list of dependencies in resourcemanager and resourcemanagerhybrid directory.

2022-04-18 19:14 UTC, alzimmermsft approved these changes

2022-04-19 01:59 UTC, weidongxu-microsoft approved these changes
What does azure-sdk-template do?

2022-04-19 15:05 UTC, JimSuplizio requested changes
The resourcemanager tags are all set to use azure-resourcemanager's version instead of the versions of their respective libraries. 
The resourcemanagerhybrid has no tags but there may be a reason for that which I've asked.

2022-04-19 15:05 UTC, JimSuplizio commented on sdk/resourcemanagerhybrid/pom.xml
> +          <version>1.0.0-hybrid</version>
@srnagar why do these have a non-standard version and no version tag?

2022-04-19 18:09 UTC, srnagar commented
@weidongxu-microsoft  the azure-sdk-template is a template for creating new client libraries. The structure of all new client libraries should be similar to the template module. It's also used to test the release pipelines and are not intended for customer use.

2022-04-19 19:08 UTC, merged