Create a single SHA for patch releases
Azure/azure-sdk-for-java pull request #28551
Opened 2022-04-27 16:27 UTC by pallavit

1. This script generates a single SHA for patch releases - with the changelog, readme and other sources in the releasable state
2. Creates a separate branch for the BOM releases - with the snapshot of the version_client.txt file.
3. Generates a report containing the name of the branches (one for BOM and other for artifacts) and the name of each artifact that needs to be patched.

Fixes #28535

2022-05-12 19:17 UTC, JimSuplizio approved these changes
Thanks for making these updates @pallavit.

2022-06-23 19:31 UTC, JimSuplizio requested changes

2022-06-23 19:31 UTC, JimSuplizio commented on eng/pipelines/bompreparation.yml
> +      - eng/pipelines/bompreparation.yml
```suggestion
pr: none
```
We don't want this ever being triggered other than manually.

2022-06-27 16:56 UTC, pallavit commented
@JimSuplizio I have updated the pipeline trigger. Let me know if you have any other concerns. I have also set the PR to auto-merge so unless you have any other comments, your approval will merge this PR.
/cc: @vcolin7, @srnagar

2022-06-27 18:13 UTC, JimSuplizio approved these changes
Thank you @pallavit for updating the triggers. This isn't a pipeline we want running unless we explicitly run it.

2022-06-27 18:14 UTC, merged