Fixed Store Response headers case insensitivity
Azure/azure-sdk-for-java pull request #29210
Opened 2022-06-03 19:30 UTC by kushagraThapar

* Fixed Store Response headers case insensitivity
* Response headers are case insensitive, and they can change the casing anytime.

2022-06-03 19:40 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2022-06-03 20:18 UTC, kushagraThapar commented on sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/StoreClient.java
> +        for (int idx = 0; idx < storeResponse.getResponseHeaderNames().length; idx++) {
That's what I plan to do, but as part of the above linked github issue future PR. 
In this PR, I just reverted to the old state of v4 SDK, so as to make sure if compute or gateway changes anything, we don't break existing customers.

2022-06-03 20:23 UTC, kushagraThapar commented
/azp run java - cosmos - tests

2022-06-06 20:19 UTC, xinlian12 commented
/azp run java - cosmos - tests

2022-06-06 20:19 UTC, xinlian12 commented
/azp run java - cosmos - tests

2022-06-06 21:06 UTC, xinlian12 commented
/azp run java - cosmos - tests

2022-06-07 09:06 UTC, FabianMeiswinkel requested changes

2022-06-07 09:06 UTC, FabianMeiswinkel commented on sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/StoreResponse.java
> -        responseHeaders = new ConcurrentHashMap<>(headerMap);
Why not just use java.util.concurrent.ConcurrentSkipListMap here instead?

2022-06-07 14:27 UTC, FabianMeiswinkel commented
Here is an alternative which does not fallback to arrays - https://github.com/Azure/azure-sdk-for-java/pull/29268

2022-06-07 16:56 UTC, xinlian12 commented
close due to PR https://github.com/Azure/azure-sdk-for-java/pull/29268

2022-06-07 16:56 UTC, closed without merging