Fix Attestation Readme Issue #28411
Azure/azure-sdk-for-java pull request #29333
Opened 2022-06-09 08:35 UTC by hongli750210

Fixes #28411

@joshfree, @lmazuel and @LarryOsterman for notification.

2022-06-09 09:02 UTC, v-xuto commented
/azp run java - attestation - ci

2022-06-09 14:27 UTC, LarryOsterman requested changes

2022-06-09 14:27 UTC, LarryOsterman commented on sdk/attestation/azure-security-attestation/README.md
> +- [Retrieve Token Certificates](#retrieve-token-certificates)
Change the anchor, not the link for `Retrieve Token Certificates`. The old name is better.

2022-06-09 14:27 UTC, LarryOsterman commented on sdk/attestation/azure-security-attestation/README.md
> +- [Set unsigned attestation policy (AAD clients only)](#set-unsigned-attestation-policy-aad-clients-only)
Change the anchor, not the link for `Set unsigned attestation policy`

2022-06-09 14:27 UTC, LarryOsterman commented on sdk/attestation/azure-security-attestation/README.md
> +- [List attestation signing certificates](#list-attestation-signing-certificates)
Change the anchor, not the link for `List policy management certificates`.

Bonus: You might consider changing the name from `policy management certificates` to `Isolated Mode management certificates` - the name `policy management certificates` does not fully encapsulate what these certificates are used for.

2022-06-09 14:27 UTC, LarryOsterman commented on sdk/attestation/azure-security-attestation/README.md
> +- [Add attestation signing certificate](#add-attestation-signing-certificate)
Change the anchor, not the link for `Add policy management certificate`

2022-06-10 02:52 UTC, hongli750210 commented on sdk/attestation/azure-security-attestation/README.md
> +- [Remove attestation signing certificate](#remove-attestation-signing-certificate)
Rollbacked link name to old name and changed the anchor.

2022-06-10 21:12 UTC, LarryOsterman approved these changes

2022-07-04 08:02 UTC, v-xuto commented
@LarryOsterman Please help merge this PR. Thanks a lot.

2022-07-05 16:29 UTC, merged