Remove netty.transport.epoll in azure-cosmos module-info
Azure/azure-sdk-for-java pull request #29408
Opened 2022-06-13 09:14 UTC by Netyyyy

Due to `netty-transport-epoll` changing its module name in version 4.1.77.Final https://github.com/netty/netty/issues/12456,
remove it from `module-info.java` for better supporting multiple Spring Boot versions

2022-06-13 09:14 UTC, Netyyyy commented
/azp run java - spring - tests

2022-06-13 09:15 UTC, Netyyyy commented
/azp run java - cosmos - tests

2022-06-13 09:15 UTC, Netyyyy commented
/azp run java - keyvault - tests

2022-06-13 09:20 UTC, Netyyyy commented
@kushagraThapar please take a look and make sure it doesn't cause any other problems, thanks!

2022-06-13 09:39 UTC, saragluna commented
Some more context on this:

| Netty Version | Description| Automatic Module Name|
|--|--|--|
|<= 4.1.69| Netty epoll classes and native shipped in one library|io.netty.transport.epoll|
|<=4.1.76| Netty epoll classes and native shipped in two libraries| io.netty.transport.epoll & io.netty.transport.classes.epoll|
|> 4.1.77| Netty epoll classes and native shipped in two libraries |  io.netty.transport.epoll.\<native-identifier> & io.netty.transport.classes.epoll

2022-06-13 12:13 UTC, saragluna commented
Hi @kushagraThapar, please help take a look at this PR, we're trying to upgrade the dependencies to Spring Boot 2.7.0 this month, and probably we need to release a version for Spring Data Cosmos with Spring Data Commons 2.7.0.

2022-06-13 14:16 UTC, FabianMeiswinkel requested changes
This change needs further discussion - blocking the PR to make sure there is a consensus before it gets merged.

2022-06-16 21:33 UTC, kushagraThapar commented
@saragluna / @Netyyyy  - ack on the PR review, @xinlian12 has another PR for testing purposes here - https://github.com/Azure/azure-sdk-for-java/pull/29509 
However, since this is a breaking change, I am wondering how do we want to tackle this. @alzimmermsft @joshfree  thoughts?

2022-06-28 08:11 UTC, closed without merging