Examples of Using Accessor Pattern to Remove *Bridge Classes
Azure/azure-sdk-for-java pull request #29544
Opened 2022-06-17 18:52 UTC by alzimmermsft

This PR is an example of using the interface accessor pattern to reduce/remove the *Bridge classes in azure-cosmos.

2022-06-17 19:04 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-cosmos](https://apiview.dev/Assemblies/Review/e6fb9755679a49159669890a507453ca)

2022-06-17 20:26 UTC, alzimmermsft commented
/azp run java - cosmos - tests

2022-06-20 11:46 UTC, FabianMeiswinkel requested changes
Please follow this pattern instead

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/ImplementationBridgeHelpers.java

https://github.com/Azure/azure-sdk-for-java/blob/99a587f040af695429bffef3a773cde9a7cd0d3d/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosClientBuilder.java#L868-L910

Not just for consistency raesons ( which I still consider critical) - but we ran into hard to debug issues because static ctors are not really thread-safe in java (when different class loaders are used) see below PRs for context
https://github.com/Azure/azure-sdk-for-java/pull/28912
https://github.com/Azure/azure-sdk-for-java/pull/29002
https://github.com/Azure/azure-sdk-for-java/pull/28961

2022-06-30 12:28 UTC, alzimmermsft commented
Closing as prototyping doesn't use proper pattern

2022-06-30 12:28 UTC, closed without merging