Remove coverage profile from service pom
Azure/azure-sdk-for-java pull request #29572
Opened 2022-06-20 20:42 UTC by srnagar

This PR updates the service poms to remove the `coverage` profile. The pom file required to create aggregate coverage report per service is [now generated](https://github.com/Azure/azure-sdk-for-java/pull/29035) in the pipeline. So, the service poms can go back to being track agnostic and contain only the list of modules.

2022-06-20 20:45 UTC, alzimmermsft approved these changes

2022-06-20 20:46 UTC, digimaun approved these changes

2022-06-20 22:03 UTC, alzimmermsft commented
/azp run java - core

2022-06-21 01:18 UTC, weidongxu-microsoft approved these changes

2022-06-21 01:22 UTC, saragluna requested changes

2022-06-21 15:24 UTC, srnagar commented on sdk/spring-experimental/pom.xml
> -  </profiles>
Yes, I have add the dev and default profiles back.

2022-06-21 19:12 UTC, JimSuplizio commented
I'm going to override check enforcer. The resourcemanagerhybrid libraries and incorrect triggers caused the pipeline that should not have run to get run. Those triggers were fixed as part of this PR (thank you @srnagar)

2022-06-22 01:35 UTC, saragluna approved these changes
LGTM for Spring changes.

2022-06-22 01:35 UTC, saragluna commented on sdk/spring/scripts/compatibility_insert_dependencymanagement.py
> +            return
Thanks for this change!

2022-06-22 06:43 UTC, merged