Update AzureSpringBootVersionVerifier's log
Azure/azure-sdk-for-java pull request #30370
Opened 2022-08-10 01:40 UTC by Netyyyy

The current debug log is repeated and not smooth
 ```
2022-08-09 13:58:51.623 DEBUG 1739 --- [           main] s.c.a.i.c.AzureSpringBootVersionVerifier : Version found in Boot manifest [2.6.7]  
2022-08-09 13:58:51.623 DEBUG 1739 --- [           main] s.c.a.i.c.AzureSpringBootVersionVerifier : Version found in Boot manifest [2.6.7]
```
Change it in this PR

2022-08-10 01:48 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2022-09-07 01:25 UTC, saragluna requested changes

2022-09-07 01:25 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/compatibility/AzureSpringBootVersionVerifier.java
> +            LOGGER.info("Cannot check current Spring Boot version from Spring Cloud Azure supported versions.");
This log doesn't make sense. The `version` returns from the `getVersionFromManifest()` method, but the log is `from Spring Cloud Azure supported versions.` What does this mean?

2022-09-07 01:25 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/compatibility/AzureSpringBootVersionVerifier.java
> +                        + "versions [{}].", acceptedVersion);
`The current Spring Boot version matches Spring Cloud Azure accepted version [{}]`

2022-09-07 01:25 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/compatibility/AzureSpringBootVersionVerifier.java
> +        LOGGER.debug("Currently running on Spring Boot version [{}], trying to match it in Spring Cloud Azure "
`Currently running on Spring Boot version [{}], trying to match it with Spring Cloud Azure accepted version [{}].`

2022-09-07 01:44 UTC, stliu approved these changes

2022-09-07 02:09 UTC, saragluna approved these changes

2022-09-07 02:16 UTC, merged