Update terminology from credentialfree to passwordless
Azure/azure-sdk-for-java pull request #30788
Opened 2022-09-05 15:18 UTC by backwind1233

1. Update terminology from credentialfree to passwordless.
2. Add some links to README.MD

2022-09-05 15:19 UTC, backwind1233 commented
https://github.com/Azure/azure-sdk-for-java/issues/30787

2022-09-08 10:23 UTC, saragluna requested changes

2022-09-08 10:23 UTC, saragluna commented on sdk/boms/spring-cloud-azure-dependencies/pom.xml
> +      <dependency>
Please add some description here to explain why we are adding this dependency.

2022-09-08 10:23 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/jdbc/JdbcPropertiesBeanPostProcessor.java
> +import static com.azure.spring.cloud.service.implementation.identity.credential.provider.SpringTokenCredentialProvider.PASSWORDLESS_TOKEN_BEAN_NAME;
Shouldn't this be PASSWORDLESS_TOKEN_**CREDENTIAL**_BEAN_NAME?

2022-09-09 02:18 UTC, backwind1233 commented
Linke issue: https://github.com/Azure/azure-sdk-for-java/issues/30787

2022-09-09 02:22 UTC, saragluna requested changes

2022-09-09 02:22 UTC, saragluna commented on sdk/boms/spring-cloud-azure-dependencies/pom.xml
> +      <!-- TODO (zhihaoguo): specify the version of azure-identity, we need to remove this before merging into main -->
Pin the version of azure-identity to 1.6.0-beta.1 for we want to use the caching ability for MI.

2022-09-09 09:05 UTC, saragluna approved these changes

2022-09-09 09:05 UTC, merged