fix benchmark
Azure/azure-sdk-for-java pull request #30781
Opened 2022-09-03 02:46 UTC by xinlian12

Fix the shouldContinue() logic in benchmark

2022-09-03 02:57 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2022-09-12 17:15 UTC, kushagraThapar requested changes
@xinlian12 looks like there is an Archive zip file added to the repo through this PR, we should remove it if it is not necessary.

2022-09-13 01:01 UTC, xinlian12 commented
> @xinlian12 looks like there is an Archive zip file added to the repo through this PR, we should remove it if it is not necessary.
Thanks, that is a good catch. Has removed

2022-09-13 19:50 UTC, kushagraThapar approved these changes

2022-09-15 00:59 UTC, merged