Add `OAuth2ErrorResponseErrorHandler` for `restTemplate` used in AzureAD
Azure/azure-sdk-for-java pull request #30786
Opened 2022-09-05 07:18 UTC by chenrujun

1. Add `OAuth2ErrorResponseErrorHandler` for `restTemplate` used in `AzureAD`.

2. Use 2 `restTemplate` bean. Because `OAuth2ErrorResponseErrorHandler` is required when retrieve an access token. When retrieve key to validate access token. Then `OAuth2ErrorResponseErrorHandler` must not be used.

2022-09-05 07:19 UTC, chenrujun commented
Hi, @saragluna , @moarychan , please help to review this PR when you have time.

2022-09-05 07:23 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[spring-cloud-azure-autoconfigure](https://apiview.dev/Assemblies/Review/9fc11d1d8c0942d7a411388179c07dd6)

2022-09-06 02:16 UTC, moarychan requested changes

2022-09-06 02:16 UTC, moarychan commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aadb2c/configuration/AadB2cOAuth2ClientConfiguration.java
> +            @Qualifier(AZURE_AD_ACCESS_TOKEN_RETRIEVER_REST_OPERATIONS_BEAN_NAME) RestOperations restOperations) {
No @Qualifier annotation is required.

2022-09-06 02:16 UTC, moarychan commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aadb2c/configuration/AadB2cOAuth2ClientConfiguration.java
> +            @Qualifier(AZURE_AD_ACCESS_TOKEN_RETRIEVER_REST_OPERATIONS_BEAN_NAME) RestOperations restOperations) {
the same.

2022-09-06 02:16 UTC, moarychan commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadOAuth2ClientConfiguration.java
> +            @Qualifier(AZURE_AD_ACCESS_TOKEN_RETRIEVER_REST_OPERATIONS_BEAN_NAME) RestOperations restOperations,
No @qualifier annotation is required.

2022-09-06 02:26 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadRestOperationConfiguration.java
> +    public RestOperations azureAdAccessTokenRetrieverRestOperations(RestTemplateBuilder builder) {
In scenarios like `resource_server_with_obo` and `web_application_and_resource_server`, both the 2 bean should be created.

![image](https://user-images.githubusercontent.com/13167207/188533898-4bbc1b5f-f75b-409d-8160-5bfd49a635cc.png)

2022-09-06 02:47 UTC, moarychan commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadRestOperationConfiguration.java
> +    public RestOperations azureAdAccessTokenRetrieverRestOperations(RestTemplateBuilder builder) {
> In scenarios like `resource_server_with_obo` and `web_application_and_resource_server`, both the 2 bean should be created.

Yes, the rest operation bean can be used for `web_application` or `resource_server` respectively, I'm not sure it's necessary to create on demand.

2022-09-07 09:19 UTC, saragluna requested changes

2022-09-07 09:19 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadOAuth2ClientConfiguration.java
> +            @Qualifier(AZURE_AD_ACCESS_TOKEN_RETRIEVER_REST_OPERATIONS_BEAN_NAME) RestOperations restOperations,
Inject this bean through the constructor. We don't need to add qualifier everywhere in this class.

2022-09-07 09:19 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadResourceServerConfiguration.java
> +                                 @Qualifier(AZURE_AD_ACCESS_TOKEN_VALIDATOR_REST_OPERATIONS_BEAN_NAME) RestOperations restOperations) {
Same here, I suggest we inject this bean via ctor.

2022-09-07 09:19 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadRestOperationConfiguration.java
>  public class AadRestOperationConfiguration {
I suggest we split this class into two classes, `AadOAuth2ClientRestOperationConfiguration` and `AadResourceServerRestOperationConfiguration`.

2022-09-07 09:19 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadRestOperationConfiguration.java
>  public class AadRestOperationConfiguration {
And on `AadOAuth2ClientConfiguration` import this first one, on `AadResourceServerConfiguration` import the other. I agree with what @moarychan said, when only either oauth2 client or resource server is used, we don't need both beans in the context.

2022-09-07 09:19 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadRestOperationConfiguration.java
> +
Better put these bean names in `AadResourceServerConfiguration`, and we better call them by wider scenario, like `oauth2 client` and `resource server`

2022-09-07 09:19 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aadb2c/AadB2cResourceServerAutoConfiguration.java
> +            @Qualifier(AZURE_AD_ACCESS_TOKEN_VALIDATOR_REST_OPERATIONS_BEAN_NAME) RestOperations restOperations,
Inject this bean via ctor.

2022-09-08 01:46 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadRestOperationConfiguration.java
> +    public RestOperations azureAdAccessTokenRetrieverRestOperations(RestTemplateBuilder builder) {
It won't be a heavy cost to create a bean even if it's never used.

2022-09-08 07:15 UTC, saragluna requested changes

2022-09-08 07:15 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/test/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadOauth2ClientRestOperationConfigurationTest.java
> +        new ApplicationContextRunner()
We can remove these two `public`, test classes and methods can be package-private.

2022-09-08 07:15 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/test/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadOauth2ResourceServerRestOperationConfigurationTest.java
> +    @Test
Same here.

2022-09-08 07:15 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/test/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadOauth2RestOperationConfigurationTestUtil.java
> +public class AadOauth2RestOperationConfigurationTestUtil {
Same

2022-09-08 07:15 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/test/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadOauth2RestOperationConfigurationTestUtil.java
> +    }
We don't need this static method. Inlining this in your method will make it more readable.

2022-09-08 07:15 UTC, saragluna commented on sdk/spring/spring-cloud-azure-autoconfigure/src/test/java/com/azure/spring/cloud/autoconfigure/aad/implementation/AadOauth2RestOperationConfigurationTestUtil.java
> +    }
If this is a util class, we can try to make this method more generic, 

```java
static <T> boolean hasXXX(List<T> list, Class<> clazz) {
        return list.stream()
                .anyMatch(converter -> xxx);
    }

```

2022-09-09 01:26 UTC, chenrujun commented
FYI: PR to update reference doc: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3570

2022-09-09 02:18 UTC, saragluna approved these changes

2022-09-09 05:17 UTC, merged