Update README of azure-identity-providers-jdbc-[mysql/postgresql] libraries
Azure/azure-sdk-for-java pull request #31380
Opened 2022-10-11 09:19 UTC by backwind1233

Make some improvements:

Update README of azure-identity-providers-jdbc-mysql
Update README of azure-identity-providers-jdbc-postgresql
Docs
[azure-storage-blob](https://github.com/Azure/azure-sdk-for-java/tree/8ec2bcfa43c90aa5e716b8cf1ac212e9b8000cdc/sdk/storage/azure-storage-blob)
[azure-identity](https://github.com/Azure/azure-sdk-for-java/tree/8ec2bcfa43c90aa5e716b8cf1ac212e9b8000cdc/sdk/identity/azure-identity).

2022-10-11 10:14 UTC, saragluna commented on sdk/jdbc/azure-identity-providers-jdbc-postgresql/README.md
> +| [Quick start][quick_start_postgresql]
Quickstart

2022-10-11 14:42 UTC, saragluna commented on sdk/jdbc/azure-identity-providers-core/README.md
> +This package contains a template framework to get a token from Azure AD.
```suggestion
This package contains a template framework to get a token from Azure Active Directory (Azure AD).
```

2022-10-11 14:44 UTC, saragluna requested changes

2022-10-11 14:44 UTC, saragluna commented on sdk/jdbc/azure-identity-providers-jdbc-mysql/README.md
> +Now the package is not included in the `azure-sdk-bom`, so it can only be included via a direct dependency.
```suggestion
The package is not part of the `azure-sdk-bom` now, so it can only be included via a direct dependency.
```

2022-10-11 14:44 UTC, saragluna commented on sdk/jdbc/azure-identity-providers-jdbc-mysql/README.md
> +[Source code][source] | [API reference documentation][docs] | [Product documentation][product_docs]
A toc would be great to have

2022-10-12 02:08 UTC, backwind1233 commented
Hi @fangjian0423 could you help review this PR？

2022-10-12 09:25 UTC, fangjian0423 approved these changes
LGTM

2022-10-12 15:00 UTC, saragluna requested changes

2022-10-13 05:49 UTC, backwind1233 commented on sdk/jdbc/azure-identity-providers-jdbc-mysql/README.md
> +- [Azure identity JDBC MySQL plugin library for Java](#azure-identity-jdbc-mysql-plugin-library-for-java)
I am still working on this doc, will update.

2022-10-14 08:13 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2022-10-14 08:32 UTC, saragluna approved these changes

2022-10-14 09:38 UTC, merged