Marked packages in release
Azure/azure-sdk-for-java pull request #32200
Opened 2022-11-16 23:04 UTC by jeet1995

## azure-cosmos
### 4.39.0 (2022-11-16)

#### Bugs Fixed
* Fixed a rare race condition for `query plan` cache exceeding the allowed size limit - See [PR 31859](https://github.com/Azure/azure-sdk-for-java/pull/31859)
* Added improvement in `RntbdClientChannelHealthChecker` for detecting continuous transit timeout. - See [PR 31544](https://github.com/Azure/azure-sdk-for-java/pull/31544)
* Fixed an issue in replica validation where addresses may have not sorted properly when replica validation is enabled. - See [PR 32022](https://github.com/Azure/azure-sdk-for-java/pull/32022)
* Fixed unicode char handling in Uris in Cosmos Http Client. - See [PR 32058](https://github.com/Azure/azure-sdk-for-java/pull/32058)
* Fixed an eager prefetch issue to lazily prefetch pages on a query - See [PR 32122](https://github.com/Azure/azure-sdk-for-java/pull/32122)

#### Other Changes
* Shaded `MurmurHash3` of apache `commons-codec` to enable removing of the `guava` dependency - CVE-2020-8908 - See [PR 31761](https://github.com/Azure/azure-sdk-for-java/pull/31761)
* Updated test dependency of `testng` to version 7.5 - See [PR 31761](https://github.com/Azure/azure-sdk-for-java/pull/31761)
* Reduced the logging noise level on CancellationExceptions from `RntbdReporter.reportIssue`. - See [PR 32175](https://github.com/Azure/azure-sdk-for-java/pull/32175)

## azure-cosmos-spark_3-1_2-12
### 4.15.0 (2022-11-16)

#### Other Changes
* Fixed shading instructions to correct dependency issues in Azure Synapse with version 4.14.0 and 4.14.1. - See [PR 31980](https://github.com/Azure/azure-sdk-for-java/pull/31980) 
* Reduced the logging noise level on CancellationExceptions from `RntbdReporter.reportIssue`. - See [PR 32175](https://github.com/Azure/azure-sdk-for-java/pull/32175)

## azure-cosmos-spark_3-2_2-12
### 4.15.0 (2022-11-16)

#### Other Changes
* Fixed shading instructions to correct dependency issues in Azure Synapse with version 4.14.0 and 4.14.1. - See [PR 31980](https://github.com/Azure/azure-sdk-for-java/pull/31980)
* Reduced the logging noise level on CancellationExceptions from `RntbdReporter.reportIssue`. - See [PR 32175](https://github.com/Azure/azure-sdk-for-java/pull/32175)

## azure-cosmos-spark_3-3_2-12
### 4.15.0 (2022-11-16)

#### Other Changes
* Fixed shading instructions to correct dependency issues in Azure Synapse with version 4.14.0 and 4.14.1. - See [PR 31980](https://github.com/Azure/azure-sdk-for-java/pull/31980)
* Reduced the logging noise level on CancellationExceptions from `RntbdReporter.reportIssue`. - See [PR 32175](https://github.com/Azure/azure-sdk-for-java/pull/32175)

## azure-cosmos-encryption
### 1.9.0 (2022-11-16)
* Updated `azure-cosmos` to version `4.39.0`.

## azure-spring-data-cosmos
### 3.30.0 (2022-11-16)
### Other Changes
* Updated `azure-cosmos` to version `4.39.0`.

2022-11-16 23:12 UTC, FabianMeiswinkel requested changes
Spark md files are missing some version changes - readme.md for example - search for 4.14.1 in md files and you'll find the places.

2022-11-16 23:48 UTC, kushagraThapar approved these changes
LGTM, thanks @jeet1995 !

2022-11-17 00:28 UTC, FabianMeiswinkel commented on sdk/cosmos/azure-cosmos-spark_3_2-12/docs/quick-start.md
> +  - [Azure Databricks Runtime 11.3 LTS with Spark 3.3.0](https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/11.3)
```suggestion
  - [Azure Databricks Runtime 11.3 LTS with Spark 3.3.0](https://learn.microsoft.com/azure/databricks/release-notes/runtime/11.3)
```

2022-11-17 00:29 UTC, FabianMeiswinkel approved these changes
LGTM - Thanks

2022-11-17 01:30 UTC, merged