Preparing libraries for automated patch releases
Azure/azure-sdk-for-java pull request #32750
Opened 2023-01-03 12:37 UTC by vcolin7

Before getting into the specifics of this PR, I wanted to note that I am aware there was work done by @pallavit earlier to allow for preparing all of our data plane libraries for a patch release and generating a list of these artifacts for a release pipeline to consume. That work will be useful in the future once all of the data plane libraries opt into this process (there are some caveats to consider for a few libraries).

For the time being, I came up with the following as a POC that does the same for a specific set of libraries by adding a small script that reuses `generatepatch.ps1`, which we had been using for a while, as well as a document that contains a list of artifacts that have opted-in to be a part of the automated patch release process.

An automated patch release for a library contains updates to a library's dependencies, CHANGELOG and README only, compared to the latest stable version. No other changes shall be included as part of such a release.

Currently, the process only handles data plane libraries (those under the `com.azure` group ID), meaning this will not work for management plane or Spring libraries.

Libraries listed in the `patch_release_client.txt` file here will not be released for a given release cycle if a new stable version for them has been marked for release in our Azure DevOps portal either manually or by using the `/eng/common/scripts/Prepare-Release.ps1` script. Marking a library for a beta release will not affect this process. **This Azure DevOps check is not part of this PR and will be added in a future one.**

About the changes to the pipeline templates, I noticed that calling `/eng/versioning/set_versions.py` with the `--prep-source-testing` option would cause the check for unreleased dependencies to fail every time when trying to release a new patch, as most dependencies would be set to the "current" version beforehand, which is usually a beta. Since we control when we set up a release branch based on `main`, we can wait for libraries like Azure Core, Azure Identity or Azure Storage to be released before we set out to release these simple patches. If these kinds of libraries opt into releasing patches automatically, we can include them in the list of libraries to release and get everything out at once without much trouble as well.

Finally, I keep seeing [this Maven cache error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2087780&view=logs&j=94b2cd3b-5f5c-583d-8092-c4b4007c9498&t=93422b2a-8d6a-47df-a225-a664297c2212&l=24) in my test pipeline runs, do you know why this might be happening @JimSuplizio, @benbp, @hallipr, @weshaggard?

2023-01-09 18:23 UTC, JimSuplizio requested changes
//CC @joshfree 
In general, I'm fine with the changes. The one thing I do have a problem with is the eng/pipelines/patch_release_client.txt file, which is a file that contains a list of libraries that have opted-in to the patch release. The fact of the matter is that every library in the [azure-sdk-bom](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/azure-sdk-bom/pom.xml) should not have a choice of whether or not to "opt-in" to the patch release process. This patch release process serves two purposes:

1. ensure that if we need to update a dependency that everything affected by that update is released accordingly
2. ensure that we're releasing the azure-sdk-bom with the correct versions that all have the correct set of non-conflicting dependencies

We can't have partner teams, that are in the azure-sdk-bom, opting out of this process. This would do nothing but delay and add additional unnecessary complexity to something that's already non-trivial. The purpose of the patch-release is to release the libraries with the updated dependencies and then release the azure-sdk-bom. Anything else, in between those two steps is going to cause problems.

2023-01-09 18:34 UTC, pallavit commented
@vcolin7 thank you for doing this! This is exciting :). A few things to consider

> Libraries listed in the patch_release_client.txt file here will not be released for a given release cycle if a new stable version for them has been marked for release in our Azure DevOps portal either manually or by using the /eng/common/scripts/Prepare-Release.ps1 script. Marking a library for a beta release will not affect this process. This Azure DevOps check is not part of this PR and will be added in a future one.

I had evaluated this at some point and had decided against it because it is really hard to ensure atomicity between 2 parallel systems. And given we any way do a ton of releases, if we truly get into the state of releasing automatically - we may end up releasing a few wasteful patches but it wouldn't be the end of the world and potentially be simpler in code to not check this. Just another perspective :)

I am also curious about this

> that does the same for a specific set of libraries by adding a small script that reuses generatepatch.ps1, which we had been using for a while, as well as a document that contains a list of artifacts that have opted-in to be a part of the automated patch release process.

This is a great starting point and makes the process simpler and I can think of some blacklisted packages that would like to opt-out but other than that what packages would you ideally like to not include? How are you going to keep this list accurate? How do you add to this list any new GA's? The BOM script had some code that actually figured out the list of packages that should be updated, perhaps you could modify it to create a new patch_release_client.txt and compare the contents of old and new files, that way it gives you errors/warnings when the contents differ and you can make a more educated decision on what all to include.

2023-01-09 18:44 UTC, JimSuplizio commented
> Finally, I keep seeing [this Maven cache error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2087780&view=logs&j=94b2cd3b-5f5c-583d-8092-c4b4007c9498&t=93422b2a-8d6a-47df-a225-a664297c2212&l=24) in my test pipeline runs, do you know why this might be happening @JimSuplizio, @benbp, @hallipr, @weshaggard?

This is for everyone else's benefit. The reason why this was happening is because of the generate-project-list-and-cache-maven-repository.yml, which tries to restore the repository, adds the post job that tries to cache the repository. This wouldn't normally be a problem if anything was built but the Analyze and Verify job doesn't build anything so there's no repository to cache. I'd added an input boolean, defaulting to true so nothing existing is affected, to not restore the cache for that particular job.

2023-01-24 23:49 UTC, JimSuplizio approved these changes
@vcolin7, as per our chat, the changes requested from my first review were more ethereal, looking to remove the opt-out stuff. Since then we've chatted and I know, for the moment, that the opt-out stuff is going to remain in until we can meet and convince partner teams otherwise.

2023-01-25 01:58 UTC, merged