Remove kafka info from headers
Azure/azure-sdk-for-java pull request #33210
Opened 2023-01-30 09:01 UTC by Netyyyy

As title.
Fixes https://github.com/Azure/azure-sdk-for-java/issues/32777.

2023-01-31 01:10 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-02-03 06:59 UTC, saragluna requested changes

2023-02-03 06:59 UTC, saragluna commented on sdk/spring/spring-messaging-azure-eventhubs/src/main/java/com/azure/spring/messaging/eventhubs/support/converter/EventHubsMessageConverter.java
> +            } else if (TARGET_PROTOCOL.contains(key)) {
What does this mean `TARGET_PROTOCOL.contains(key)`?

2023-02-07 08:53 UTC, saragluna requested changes

2023-02-07 10:00 UTC, saragluna approved these changes

2023-02-07 10:01 UTC, saragluna commented
LGTM, but it's weird to process a Spring Cloud Function header in the spring messaging layer.

2023-02-08 01:40 UTC, moarychan approved these changes
LGTM for the changelog, please check whether this change is valid for the Service Bus side.

2023-02-08 02:05 UTC, merged