[Confidential Ledger] Increment SDK Release
Azure/azure-sdk-for-java pull request #33367
Opened 2023-02-07 13:34 UTC by Xamrmo

# Description
Prepare Confidential Ledger patch release for February 2023.

2023-02-07 16:11 UTC, alzimmermsft approved these changes

2023-02-08 01:17 UTC, vcolin7 requested changes
Hi @Xamrmo, the PR looks good but before releasing you'll need to pull `main` into this branch or cherry-pick [this commit](https://github.com/Azure/azure-sdk-for-java/commit/5a2d508df50325279eb41baa9b6f59729fcef640), as it fixes an issue that would cause libraries you marked not for release to get released anyways when running the pipeline.

2023-02-08 11:39 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-02-08 17:27 UTC, joshfree approved these changes

2023-02-09 00:18 UTC, vcolin7 approved these changes

2023-02-09 00:18 UTC, merged