Make default partition behavior be a round-robin assignment when using Spring Cloud Azure EventHubs binder
Azure/azure-sdk-for-java pull request #33361
Opened 2023-02-07 08:00 UTC by Netyyyy

As title.
Fixes https://github.com/Azure/azure-sdk-for-java/issues/32816

2023-02-07 08:07 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-02-07 08:48 UTC, saragluna commented
@moarychan please help review.

2023-02-07 08:48 UTC, saragluna requested changes

2023-02-07 08:48 UTC, saragluna commented on sdk/spring/spring-cloud-azure-stream-binder-eventhubs/src/test/java/com/azure/spring/cloud/stream/binder/eventhubs/EventHubsMessageChannelBinderTests.java
> +public class EventHubsMessageChannelBinderTests {
No `public`

2023-02-07 09:32 UTC, moarychan commented on sdk/spring/spring-cloud-azure-stream-binder-eventhubs/src/main/java/com/azure/spring/cloud/stream/binder/eventhubs/EventHubsMessageChannelBinder.java
>          }
Please check whether this change is necessary for the [Service Bus binder](https://github.com/Azure/azure-sdk-for-java/blob/cbbf4ba4b730c379c8b1091f2f1e3841ca323708/sdk/spring/spring-cloud-azure-stream-binder-servicebus/src/main/java/com/azure/spring/cloud/stream/binder/servicebus/ServiceBusMessageChannelBinder.java#L122).

2023-02-08 01:53 UTC, yiliuTo commented
This would be a breaking change for users, so we can mark in in the changelog.

2023-02-08 02:40 UTC, saragluna commented on sdk/spring/spring-cloud-azure-stream-binder-eventhubs/src/test/java/com/azure/spring/cloud/stream/binder/eventhubs/EventHubsMessageChannelBinderTests.java
> +    }
no public either

2023-02-08 02:47 UTC, saragluna approved these changes

2023-02-08 03:17 UTC, merged