App Configuration Spring Feature Management Usage
Azure/azure-sdk-for-java pull request #33854
Opened 2023-03-03 20:06 UTC by mrm9084

# Description

* Adds Usage Info for feature flags
* Fixes a refresh bug with feature flags when using multiple labels.

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-03-03 20:13 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-03-06 01:52 UTC, saragluna requested changes

2023-03-06 01:52 UTC, saragluna commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +    public TracingInfo(Boolean isDev, Boolean isKeyVaultConfigured, int replicaCount) {
```suggestion
    public TracingInfo(boolean isDev, boolean isKeyVaultConfigured, int replicaCount) {
```

2023-03-06 01:52 UTC, saragluna commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +    public String getValue(Boolean watchRequests) {
```suggestion
    public String getValue(boolean watchRequests) {
```

2023-03-06 01:52 UTC, saragluna commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +    private Boolean isKeyVaultConfigured = false;
```suggestion
    private boolean isDev = false;

    private boolean isKeyVaultConfigured = false;
```

2023-03-06 01:52 UTC, saragluna commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +        if ("false".equalsIgnoreCase(track)) {
nit: `Boolean.valueOf(track)`

2023-03-06 01:52 UTC, saragluna commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/FeatureFlagTracing.java
> +    public Boolean usesAnyFilter() {
`Boolean` -> `boolean`

2023-03-06 01:52 UTC, saragluna commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/AppConfigurationReplicaClient.java
> +    AppConfigurationReplicaClient(String endpoint, ConfigurationClient client, TracingInfo tracingIngo) {
```suggestion
    AppConfigurationReplicaClient(String endpoint, ConfigurationClient client, TracingInfo tracingInfo) {
```

2023-03-06 01:52 UTC, saragluna commented
@chenrujun please take a look at this PR.

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/AppConfigurationRefreshUtil.java
> +                                    break keyCheck;
Could you please try to make the depth shorter.

> ![image](https://user-images.githubusercontent.com/13167207/223632024-9b77cbe2-7314-4751-89b6-0ddeaba71715.png)

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/RequestTracingConstants.java
> +     * Constant for checking for Container App.
Keep align with other java doc. `Constant for checking for use in Container App.`

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/FeatureFlagTracing.java
> +        if (usesPercentageFilter) {
`if` -> `else if`

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/FeatureFlagTracing.java
> +            sb.append(sb.length() > 0 ? FILTER_TYPE_DELIMITER : "").append(PERCENTAGE_FILTER);
> sb.append(sb.length() > 0 ? FILTER_TYPE_DELIMITER : "")

Avoid duplicated code.

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +    private int replicaCount = 0;
The initialization is not necessary.

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +    private FeatureFlagTracing featureFlagTracing;
Field 'featureFlagTracing' may be 'final' .

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +        if (track != null && !Boolean.valueOf(track)) {
Could you please add unit test when the environment variable is?
1. null
2. empty string
3. "false"
4. "true"
5. "random string“

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +        sb.append(RequestTracingConstants.REQUEST_TYPE_KEY + "=" + requestTypeValue);
Use `append` instead of `+`

2023-03-08 06:24 UTC, chenrujun commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/TracingInfo.java
> +        sb.append(RequestTracingConstants.REQUEST_TYPE_KEY + "=" + requestTypeValue);
Same to all other places.

2023-03-08 19:44 UTC, mrm9084 commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/AppConfigurationConstants.java
> +    public static final String FEATURE_STORE_WATCH_KEY = FEATURE_FLAG_PREFIX + "*";
I'll update this to make it more clear. We use this key to watch for changes, but it does that by checking all feature flags by default.

2023-03-08 20:32 UTC, mrm9084 commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/AppConfigurationFeatureManagementPropertySource.java
> +            keyFilter = FEATURE_FLAG_PREFIX + this.keyFilter;
`StringUtils.hasText(this.keyFilter)` will not always be `true`. If you look at `FeatureFlagKeyVauleSelector`, where the `this.keyFilter` comes from, defaults to empty string.

2023-03-08 20:37 UTC, mrm9084 commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/AppConfigurationPropertySourceLocator.java
> +        }
This goes with the comment before. With the tracing info set, this can attempt to send the Feature Flag usage data back.

2023-03-08 21:05 UTC, mrm9084 commented on sdk/spring/spring-cloud-azure-appconfiguration-config/src/main/java/com/azure/spring/cloud/config/implementation/http/policy/FeatureFlagTracing.java
> +        if (usesPercentageFilter) {
Multiple of these can be true.

2023-03-14 05:49 UTC, chenrujun approved these changes
LGTM.

2023-03-14 05:52 UTC, saragluna approved these changes

2023-03-14 05:52 UTC, merged