Using VersionedClient for SeekableByteChannel Tests
Azure/azure-sdk-for-java pull request #33909
Opened 2023-03-07 21:34 UTC by ibrahimrabab

# Description

Using existing versioned service client to allow live tests to pass.

2023-03-07 21:34 UTC, ibrahimrabab commented
/azp run java - storage - tests

2023-03-07 21:41 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-03-07 22:17 UTC, ibrahimrabab commented
/azp run java - storage - tests

2023-03-08 17:02 UTC, alzimmermsft commented on sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/specialized/BlobSeekableByteChannelTests.groovy
> +        versionedCC = versionedBlobServiceClient.getBlobContainerClient(generateContainerName())
All tests in this test class will need to be regenerated as there is an additional recorded random string being generated due to the `generateContainerName()` call.

2023-03-08 19:35 UTC, ibrahimrabab commented
/azp run java - storage - tests

2023-03-08 20:17 UTC, jaschrep-msft requested changes
There's only one test that needs versioned clients. We don't need to make every test here require a versioning account. It would be better to just have this setup in the test that needs it.

2023-03-08 21:25 UTC, ibrahimrabab commented
/azp run java - storage - tests

2023-03-09 00:23 UTC, seanmcc-msft approved these changes

2023-03-09 00:24 UTC, merged