Prepare for Spring Cloud Azure 4.8.0 release
Azure/azure-sdk-for-java pull request #35130
Opened 2023-05-24 08:04 UTC by Netyyyy

# Description
Update versions, changelog and readme

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-05-24 08:11 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-05-24 08:20 UTC, Netyyyy commented on sdk/spring/CHANGELOG.md
> +### Spring Cloud Azure Appconfiguration Config
Hi @mrm9084 , FYI, please directly update CHANGELOGs here, thanks!

2023-05-24 08:44 UTC, saragluna requested changes

2023-05-24 08:44 UTC, saragluna commented on eng/versioning/version_client.txt
> +com.azure.spring:spring-cloud-azure-appconfiguration-config-web;4.7.0;4.8.0
I don't see the spring-data-cosmos here? We suppose to release it with Spring Cloud Azure together.

2023-05-24 08:44 UTC, saragluna commented on sdk/boms/spring-cloud-azure-dependencies/pom.xml
> +        <version>1.2.13</version>   <!-- NOTE: This should be updated manually. -->
should update the spring data cosmos too

2023-05-25 01:38 UTC, saragluna approved these changes

2023-05-25 01:59 UTC, merged