Fixed not moving the request start time in the responseStaticsList
Azure/azure-sdk-for-java pull request #35705
Opened 2023-06-30 23:01 UTC by rinatmini

# Description

Related issue #32899 

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-06-30 23:15 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-07-18 18:15 UTC, kushagraThapar requested changes
Overall looks great to me, thanks @rinatmini 
However, we should add some tests for this in `CosmosDiagnosticsTest` class as well. Also, it will be good to add tests for both direct and gateway mode which you can find in the `CosmosDiagnosticsTest` class.

2023-07-18 18:15 UTC, kushagraThapar commented on sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/ClientSideRequestStatistics.java
> +        return requestTimeline != null ? requestTimeline.getRequestStartTimeUTC() : null;
I don't think it can ever be null, but I like the check, lets keep it.

2023-07-22 00:04 UTC, rinatmini commented
> Overall looks great to me, thanks @rinatmini However, we should add some tests for this in `CosmosDiagnosticsTest` class as well. Also, it will be good to add tests for both direct and gateway mode which you can find in the `CosmosDiagnosticsTest` class.

Seems this issue isn't actual for gateway mode because the gateway diagnostic aggregates statistics in the gatewayStatisticsList, and direct mode in the responseStatisticsList and they use different models and gateway diagnostic doesn't have this bug.

2023-07-22 00:14 UTC, kushagraThapar approved these changes

2023-07-24 20:58 UTC, merged