Change feed start time multi write coverage
Azure/azure-sdk-for-java pull request #36257
Opened 2023-08-06 01:26 UTC by jeet1995

2023-08-07 15:45 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-08-07 17:33 UTC, kushagraThapar commented on sdk/cosmos/azure-cosmos/CHANGELOG.md
> +* Added coverage for `ChangeFeedProcessor#handleLatestVersionChanges` to read change feed from a custom start time for multi-write accounts. - See[PR 36257](https://github.com/Azure/azure-sdk-for-jav
```suggestion
* Added coverage for `ChangeFeedProcessor` in `Latest Version` change feed mode to read change feed from a custom start time for multi-write accounts. - See[PR 36257](https://github.com/Azure/azure-sdk-for-java/pull/36257)
```

2023-08-09 23:48 UTC, kushagraThapar requested changes
Blocking on running the live tests.

2023-08-10 00:25 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-13 16:19 UTC, jeet1995 commented on sdk/cosmos/azure-cosmos/CHANGELOG.md
> +* Added coverage for `ChangeFeedProcessor#handleLatestVersionChanges` to read change feed from a custom start time for multi-write accounts. - See[PR 36257](https://github.com/Azure/azure-sdk-for-jav
Fixed in next iteration.

2023-08-13 16:19 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-16 18:35 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-17 16:44 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-17 20:58 UTC, kushagraThapar commented
/azp run java - cosmos - tests

2023-08-18 02:15 UTC, kushagraThapar commented
/azp run java - cosmos - tests

2023-08-18 20:21 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-18 22:12 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-18 22:28 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-18 23:21 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-19 02:47 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-19 18:32 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-20 02:37 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-20 02:39 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-20 14:44 UTC, jeet1995 commented
/azp run java - cosmos - tests

2023-08-20 23:53 UTC, kushagraThapar approved these changes
LGTM

2023-08-21 00:02 UTC, merged