Add integration test using connetion string as auth method for App Configuration
Azure/azure-sdk-for-java pull request #36276
Opened 2023-08-08 07:50 UTC by ivywei0125

Add integration test using connetion string as auth method for App Configuration.

2023-08-08 07:52 UTC, ivywei0125 commented
/azp run java - appconfiguration - tests

2023-08-09 01:51 UTC, mrm9084 commented
/azp run java - appconfiguration - tests

2023-08-09 01:55 UTC, mrm9084 requested changes

2023-08-09 01:55 UTC, mrm9084 commented on sdk/spring/spring-cloud-azure-integration-test-appconfiguration-config/src/test/java/com/azure/spring/cloud/config/AppConfiguration.java
> +    private String authMethod;
Can you add a few comments here and a few other places. We don't touch this often. I wouldn't want to forget why we did this.

2023-08-09 02:14 UTC, mrm9084 commented
/azp run java - spring - tests

2023-08-10 16:05 UTC, mrm9084 approved these changes

2023-08-14 15:18 UTC, merged

2023-08-14 23:00 UTC, ivywei0125 commented
[like]  Yu Wei reacted to your message:
________________________________
From: Matt Metcalf ***@***.***>
Sent: Monday, August 14, 2023 3:18:36 PM
To: Azure/azure-sdk-for-java ***@***.***>
Cc: Yu Wei ***@***.***>; State change ***@***.***>
Subject: Re: [Azure/azure-sdk-for-java] Add integration test using connetion string as auth method for App Configuration (PR #36276)


Merged #36276<https://github.com/Azure/azure-sdk-for-java/pull/36276> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/Azure/azure-sdk-for-java/pull/36276#event-10088100941>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A2LH2ETJCGYC2YQAUZSS5DLXVI6UZANCNFSM6AAAAAA3IBXNE4>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>