introduce multitenancy with multiple clients
Azure/azure-sdk-for-java pull request #36358
Opened 2023-08-16 05:08 UTC by thefourtheye

This patch allows the applications to connect to multiple CosmosAsyncClients dynamically. This would enable the applications to support multi-tenancy at multiple clients level, not just at the database level or container level.

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

2023-08-16 05:09 UTC, thefourtheye commented
@microsoft-github-policy-service agree

2023-08-30 18:05 UTC, kushagraThapar requested changes
Great work @thefourtheye, apologies for the delay in PR review, didn't get the notification somehow. 

I have added few comments, let me know your thoughts on them. 

@TheovanKraay / @trande4884 please provide your feedback as well, thanks!

2023-08-30 18:26 UTC, FabianMeiswinkel requested changes
Building multi-tenancy via multiple Cosmos DB accounts and clients is not a design that will scale beyond a dozen or so tenants. I don't think we should provide a Spring-Sample for this - using it with any higher number of tenants will lead to a design problem - using multi-tenancy with separate Clients usually requires also sharding the Compute-layer - to make sure each Compute shard only connects to a subset of Cosmos Clients/Accounts. If that is not done some workarounds like LRU based Client caches etc. can help to scale to more than a few dozen tenants - but still is limited. I am against merging this PR because it could lead customers into a design trap.

2023-08-30 18:28 UTC, TheovanKraay commented
@thefourtheye firstly thanks for proposing this! We'd like to understand more about the use case. As Kushagra pointed out, multiple clients for a single application instance is not recommended. If you are looking to increase density of clients on the app side, the recommended approach would be to have a tenant per _thread_, all of which would share the same (singleton) cosmos client, but each thread/tenant can then communicate with the same, or different, databases or containers from that Spring app. There are a couple of existing samples [here ](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/cosmos/azure-spring-data-cosmos/spring3-samples/cosmos-multi-tenant-samples). Perhaps we are misunderstanding the need, so would be grateful if you could clarify why having multiple clients in a given Spring app is important/essential for the use case you have in mind?

2023-09-04 08:40 UTC, thefourtheye commented
Hello all, thanks a lot for taking a look at this.

> Since it uses multiple clients in the same application, which will most probably be running on the same JVM, it can cause issues as we don't really recommend running multiple clients in the same application.

> Building multi-tenancy via multiple Cosmos DB accounts and clients is not a design that will scale beyond a dozen or so tenants. I don't think we should provide a Spring-Sample for this - using it with any higher number of tenants will lead to a design problem

> multiple clients for a single application instance is not recommended. 

I feel that these could be elaborated a bit and I am still trying to understand the actual problem. Are we worried about the number of open connections to different Cosmos DB accounts? Or multiple client objects will take up a lot of resources in the computes? I am curious to understand why this approach will not scale or it would not be considered as a good design.

> why having multiple clients in a given Spring app is important/essential for the use case

The compliance policies expect the data of the customers to be stored in their respective geo locations and all those data will have to be accessible from a common geo location. The latency being different for different locations is acceptable in this case.

If switching between multiple clients is not supported by the SDK, I either have to deploy dedicated instances of the application for each of those geo locations by incurring additional cloud charges or I have to go with the sharding approach suggested by @FabianMeiswinkel after validating the elasticity of that solution and how well it plays with other dependencies of the application. Either way, I don't feel that the multitenancy isn't achieved at application layer, but with different deployment strategies.

Please share your thoughts.

2023-09-04 12:26 UTC, TheovanKraay commented
@thefourtheye 

"Are we worried about the number of open connections to different Cosmos DB accounts? Or multiple client objects will take up a lot of resources in the computes?"

Both - each client will be responsible for maintaining connections to replicas, which can be many thousands depending on number of partitions (in direct mode). Hence each client has quite some overhead, so we generally recommend singleton. 

But let me try to replay your requirement so we can understand it better:

The crux of your requirement is to be able to control the **account** that each tenant has access to (each account having different regions it supports), due to policies and/or regulatory requirements for data locality. Your desire is to be able to increase density at application layer by being able to refer to different Cosmos accounts dynamically in a given Spring App, instead of deploying separate app instances for each geo location. In this use case/scenario, while there might be many tenants, you would only have a few different accounts (clients), and would be directing the tenant to the account/client where geo location is appropriate. Latency arising when app instance connects to an account in a different geo location is of no concern. 

Is that a correct summary?

2023-09-07 10:21 UTC, thefourtheye commented
@TheovanKraay 

> Both - each client will be responsible for maintaining connections to replicas, which can be many thousands depending on number of partitions (in direct mode). Hence each client has quite some overhead, so we generally recommend singleton.

Thanks for confirming and explaining.

> Is that a correct summary?

That is correct. This would help me to save money.

2023-11-17 08:35 UTC, closed without merging