Fix client options flow to Http line in SDKs.
Azure/azure-sdk-for-java pull request #36382
Opened 2023-08-17 20:06 UTC by g2vinay

Fixes Client Options Wiring to Http Pipeline in following SDKs:

- Identity
- KeyVault Secrets, Keys, Certificates, Administration
- App Config
- Tables

2023-08-17 20:11 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-08-18 15:42 UTC, joshfree approved these changes
Looks good - except for the unrelated powershellcredential changes and not being linked to the customer-reported issue.

2023-08-18 15:42 UTC, joshfree commented on sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/PowershellManager.java
> -            int maxPause = Platform.isMac() ? this.waitPause : 500;
could you only include http proxy changes in this PR and also associate the PR with the customer-reported github issue for better tracking?

2023-09-08 21:00 UTC, g2vinay commented
/azp run java - identity - ci

2023-09-08 21:05 UTC, g2vinay commented
/azp run java - keyvault - ci

2023-09-08 22:21 UTC, billwert approved these changes
LGTM

2023-09-11 17:38 UTC, g2vinay commented
/azp run java - identity - ci

2023-09-13 00:35 UTC, vcolin7 requested changes
The changes for Key Vault look good, but we're missing a couple of builders: `KeyVaultBackupClientBuilder` & `KeyVaultSettingsClientBuilder`.

2023-09-13 20:40 UTC, vcolin7 approved these changes

2023-09-13 22:33 UTC, merged