Organize the Spring directory
Azure/azure-sdk-for-java pull request #36692
Opened 2023-09-11 08:52 UTC by Netyyyy

# Description

Organize the Spring directory:
1. move xxx-tests-job.yml into spring/pipeline
2. move xxx-matrix.json into spring/pipeline
3. move spring-cloud-azure-supported-spring.json into spring/pipeline

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-09-11 08:52 UTC, Netyyyy commented
/azp run java - spring - tests

2023-09-11 08:53 UTC, Netyyyy commented
/azp run java - spring-monitor - tests

2023-09-12 01:08 UTC, saragluna requested changes

2023-09-12 01:08 UTC, saragluna commented on sdk/spring/scripts/monitor_update_monitor_matrix_json.py
> +# This script is used to update sdk\spring\\pipeline\supported-version-matrix.json before compatibility check.
```suggestion
# This script is used to update sdk\spring\pipeline\supported-version-matrix.json before compatibility check.
```

2023-09-12 01:25 UTC, saragluna approved these changes

2023-09-12 02:10 UTC, Netyyyy commented
/check-enforcer override

2023-09-12 05:10 UTC, Netyyyy commented
/check-enforcer override

2023-09-12 06:40 UTC, merged

2023-09-13 16:44 UTC, kushagraThapar commented
@saragluna / @Netyyyy  - when we change any spring-data-cosmos related code, please make sure to run the cosmos ci, and spring-data-cosmos CI pipelines to validate the change. 
Looks like this change broke the cosmos CI pipelines that runs spring data cosmos CI. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3077931&view=logs&jobId=8bef1c98-23e3-5d36-ff88-ed7605b6f394

on this PR - https://github.com/Azure/azure-sdk-for-java/pull/36687#issuecomment-1717728034 

@saragluna and @Netyyyy , please work with @xinlian12 to fix this issue as quickly as possible so we can get the coverage back up, thanks!

2023-09-14 00:41 UTC, Netyyyy commented
> https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3077931&view=logs&jobId=8bef1c98-23e3-5d36-ff88-ed7605b6f394

Fix in https://github.com/Azure/azure-sdk-for-java/pull/36758