mgmt, local generation for Azure Cosmos DB
Azure/azure-sdk-for-java pull request #37132
Opened 2023-10-11 02:17 UTC by v-hongli1

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-10-11 02:25 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2023-10-11 03:16 UTC, XiaofeiCao approved these changes
Are there any manual code?

2023-10-11 03:29 UTC, v-hongli1 commented
@XiaofeiCao 
There are not any manual code.

2023-10-11 05:29 UTC, haolingdong-msft approved these changes

2023-10-11 07:53 UTC, weidongxu-microsoft requested changes
block the PR to avoid accident merge

2023-10-11 07:53 UTC, weidongxu-microsoft commented on sdk/resourcemanager/azure-resourcemanager-cosmos/src/main/java/com/azure/resourcemanager/cosmos/models/CustomerManagedKeyStatus.java
We cannot use this enum value. Need update from service.

2023-10-16 01:39 UTC, v-hongli1 commented on sdk/resourcemanager/azure-resourcemanager-cosmos/src/main/java/com/azure/resourcemanager/cosmos/models/CustomerManagedKeyStatus.java
Ok, I'll close the pr to avoid accident merge.

2023-10-16 01:39 UTC, closed without merging