mgmt, local generation for CosmosDB - 2024-02-15-preview
Azure/azure-sdk-for-java pull request #39115
Opened 2024-03-07 04:50 UTC by v-hongli1

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2024-03-07 04:57 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-03-11 04:38 UTC, weidongxu-microsoft requested changes

2024-03-11 04:38 UTC, weidongxu-microsoft commented on sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/cosmos/generated/SqlResourcesGetClientEncryptionKeySamples.java
> +     * issue%234977/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2024-02-15-preview/examples/
path is wrong again

2024-03-11 06:51 UTC, v-hongli1 commented on sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/cosmos/generated/SqlResourcesGetClientEncryptionKeySamples.java
> +     * issue%234977/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2024-02-15-preview/examples/
The codes have been generated again.

2024-03-11 07:08 UTC, weidongxu-microsoft approved these changes

2024-03-11 07:19 UTC, merged