Batch Workaround for Deserialization of Long Properties
Azure/azure-sdk-for-java pull request #40301
Opened 2024-05-22 08:37 UTC by skapur12

# Description

There is a bug in the Batch Service: all properties defined as longs in our TypeSpec are returned from the service side as strings.  
The service team is working on a fix for this issue in our next API release. 
In the meantime, this PR temporarily resolves the bug by:
1. Modifying the deserialization code to handle a string input so there is no issue with accessing these properties 
2. Adding test coverage for the deserialization of all of the long properties to determine that they are being deserialized without errors.

Once the new API is released on the service side, we will revert these temporary deserialization changes and verify that the service side logic works with the test coverage added in this PR.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2024-05-22 08:43 UTC, skapur12 commented on sdk/batch/azure-compute-batch/src/test/java/com/azure/compute/batch/JobTests.java
> +            Assertions.assertEquals(Duration.parse("PT30M"), stats.getKernelCpuTime());
I added assertions to check the values of all of the properties in every class, but that might be overkill—Would it be better to just assert the values of the long properties only? _(e.g. only readIOps, writeIOps, numSucceededTasks, numFailedTasks, numTaskRetries in this case)_

2024-05-22 21:18 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[com.azure:azure-compute-batch](https://apiview.dev/Assemblies/Review/fa98b6c9836f41dea712017ba1962b56?revisionId=728f50872afc4bffab75c97ed37ad3f8)

2024-05-28 21:41 UTC, wiboris requested changes
Please update test recordings

2024-06-07 20:00 UTC, dpwatrous approved these changes

2024-06-07 22:17 UTC, merged