Test merging feature/spring-boot-3 branch to main branch
Azure/azure-sdk-for-java pull request #41026
Opened 2024-07-05 09:01 UTC by moarychan

Draft PR, Don't review.
This PR is used to test merging **feature/spring-boot-3** branch into **main** branch.

2024-07-05 09:05 UTC, moarychan commented
/azp run java - spring - tests

2024-07-08 03:28 UTC, moarychan commented
/azp run java - spring - tests

2024-07-08 05:05 UTC, moarychan commented
/azp run java - spring - tests

2024-07-08 06:26 UTC, moarychan commented
/azp run java - spring - tests

2024-07-08 08:38 UTC, moarychan commented
/azp run java - spring - tests

2024-07-09 06:24 UTC, saragluna requested changes

2024-07-09 06:24 UTC, saragluna commented on sdk/cosmos/ci.spring.yml
> +extends:
Moving the running of the azure-spring-data-cosmos to this separate pipeline.

2024-07-09 06:24 UTC, saragluna commented on sdk/parents/azure-client-sdk-parent/pom.xml
> +      <!-- exclude to avoid so many Undefined reference errors -->
Please revert changes in this file

2024-07-09 06:24 UTC, saragluna commented on eng/versioning/external_dependencies.txt
> +# sdk\spring\pom.xml modules
please sort these lines

2024-07-10 04:09 UTC, moarychan commented
/azp run java - spring - tests

2024-07-10 06:44 UTC, moarychan commented
/azp run java - spring - tests

2024-07-10 06:52 UTC, moarychan commented
/azp run java - spring - tests

2024-07-10 07:02 UTC, moarychan commented
/azp run java - spring - tests

2024-07-10 07:52 UTC, moarychan commented
/azp run java - spring - tests

2024-07-11 05:14 UTC, moarychan commented
/azp run java - spring - tests

2024-07-11 05:26 UTC, moarychan commented
> Could you please re-enable `spring-cloud-azure-starter-monitor` and `spring-cloud-azure-starter-monitor-test`, and move them to Spring Boot 3?

Revert the deletion, the two modules are still using the Spring Boot 2.x dependencies.

2024-07-11 05:28 UTC, moarychan commented
/azp run java - spring - tests

2024-07-11 06:12 UTC, moarychan commented
/azp run java - spring - tests

2024-07-11 06:59 UTC, moarychan commented
/azp run java - spring - tests

2024-07-11 10:31 UTC, moarychan commented
/azp run java - spring - tests

2024-07-12 02:43 UTC, closed without merging