Support SNI authentication from EnvironmentCredential/DAC
Azure/azure-sdk-for-java pull request #41031
Opened 2024-07-07 18:30 UTC by billwert

When constructing a confidential client, if `AZURE_CLIENT_SEND_CERTIFICATE_CHAIN` is `true` or `1`, send the x5c chain.

Fixes #40013

2024-07-07 18:37 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-07-10 17:43 UTC, g2vinay requested changes
This feature should be supported via DAC / ENV credential only, I believe. 
Currently, it will be picked up under Client Cert Credential too.

2024-07-10 18:34 UTC, billwert commented
> This feature should be supported via DAC / ENV credential only, I believe.
> Currently, it will be picked up under Client Cert Credential too.

fixed.

2024-07-10 18:40 UTC, g2vinay approved these changes

2024-07-10 19:02 UTC, vcolin7 approved these changes

2024-07-10 19:02 UTC, lmolkova approved these changes

2024-07-10 22:05 UTC, merged