Fix Duration.between throwing an exception in some scenarios
Azure/azure-sdk-for-java pull request #42238
Opened 2024-10-09 14:31 UTC by alzimmermsft

# Description

Flips the arguments when calling `Duration.between` and negates the value when logging cache refreshes in `AccessTokenCache`. This is done as some `TokenCredential`s use a static `OffsetDateTime.MAX` as the expiration time for the token, and in some cases using `OffsetDateTime.MAX` as the second argument to `Duration.between` can cause an invalid year range exception to be thrown. The exception happens due to the implementation of `Duration.between` in some versions of Java changes the time zone of the second argument to match the first, resulting in `OffsetDateTime.MAX` needing to rollover its second, minute, hour, day, month, and year values due to the time zone change, causing its `999,999` year value (which is the max allowed by OffsetDateTime) to become `1,000,000`. Flipping the arguments to `Duration.between` resolves this as the first argument doesn't have its time zone mutated, meaning `OffsetDateTime.MAX` won't be mutated, and should be safe always as `OffsetDateTime.MAX` uses the most minimal time zone offset allowed, meaning any Temporal near the max year limit won't need to rollover values. This does force the `Duration.between` to be `.negated()` as the values have flipped.

There are a few other small changes in this PR to have `TokenCredential` subtypes implement the synchronous token retrieval API instead of relying on the default implementation in `TokenCredential`.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

2024-10-09 17:05 UTC, billwert commented on sdk/core/azure-core/src/main/java/com/azure/core/implementation/AccessTokenCache.java
> +        Duration tte = Duration.between(cache.getExpiresAt(), now).negated();
This probably deserves a comment explaining the issue and the fix.

2024-10-09 17:06 UTC, billwert commented on sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/EventHubSharedKeyCredential.java
> + * <a href="https://docs.microsoft.com/azure/event-hubs/
```suggestion
 * <a href="https://learn.microsoft.com/azure/event-hubs/
```

2024-10-09 17:06 UTC, billwert commented on sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/EventHubSharedKeyCredential.java
> + * @see <a href="https://docs.microsoft.com/azure/event-hubs/authorize-access-shared-access-signature">Authorize
```suggestion
 * @see <a href="https://learn.microsoft.com/azure/event-hubs/authorize-access-shared-access-signature">Authorize
```

2024-10-09 17:11 UTC, billwert commented on sdk/containerregistry/azure-containers-containerregistry/src/main/java/com/azure/containers/containerregistry/implementation/authentication/AccessTokenCacheImpl.java
> +        Duration tte = Duration.between(cache.getExpiresAt(), now).negated();
Comment here also.

2024-10-09 17:18 UTC, billwert commented on sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/MSIToken.java
> +        String dateToParse = !isExpiresOn ? expiresIn : expiresOn;
```suggestion
        String dateToParse = isExpiresOn ? expiresOn: expiresIn;
```

There's enough negativity in the world.

2024-10-09 17:19 UTC, billwert commented on sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusSharedKeyCredential.java
> + * <a href="https://docs.microsoft.com/azure/event-hubs/
```suggestion
 * <a href="https://learn.microsoft.com/azure/event-hubs/
```

2024-10-09 17:19 UTC, billwert commented on sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusSharedKeyCredential.java
> + * @see <a href="https://docs.microsoft.com/azure/event-hubs/authorize-access-shared-access-signature">Authorize
```suggestion
 * @see <a href="https://learn.microsoft.com/azure/event-hubs/authorize-access-shared-access-signature">Authorize
```

2024-10-09 17:37 UTC, billwert requested changes
I worry that we're leaving traps for future developers by hiding the negation in the cache implementations. Couple ideas:
1) Util method in Core for `Duration.between` with the arguments swapped and negated. (Maybe ban the `Duration.between` and make the whole codebase use the util method. Do we have a mechanism for that?)
2) Maybe this is just an `AccessToken` problem in practice, so put the helper on `AccessToken` to get the remaining life. `validDuration`, `remainingDuration`, `timeToLive`, etc?

You suggested elsewhere just using some absurdly large `OffsetDateTime` instead - I think that's fine also but would still like a constant somewhere for it and some sort of linter check to prevent mistakes in the future.

2024-10-28 18:42 UTC, billwert approved these changes

2024-10-29 15:38 UTC, alzimmermsft commented
Failing tests and pipelines are due to changes other than this PR

2024-10-29 15:52 UTC, merged